
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-30T21:28:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "87c95f6fb1af11aa195c5ea5be875c98f316fb8e",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
