[tool.poetry]
name = "whole-slide-data"
version = "0.0.14"
description = "The description of the package"

license = "MIT"

authors = [
    "Mart van Rijthoven <mart.vanrijthoven@gmail.com>"
]

readme = "README.md" 

repository = "https://github.com/DIAGNijmegen/pathology-whole-slide-data"
homepage = "https://diagnijmegen.github.io/pathology-whole-slide-data/"

keywords = ["computational-pathology", "whole-slide-data"]

[tool.poetry.dependencies]
python = "^3.8"  # Compatible python versions must be declared here
toml = "^0.9"


# # Dependencies with extras
# requests = { version = "^2.13", extras = [ "security" ] }
# # Python specific dependencies with prereleases allowed
# pathlib2 = { version = "^2.2", python = "~2.7", allow-prereleases = true }
# # Git dependencies
# cleo = { git = "https://github.com/sdispater/cleo.git", branch = "master" }
# # Optional dependencies (extras)
# pendulum = { version = "^1.4", optional = true }

# [tool.poetry.dev-dependencies]
# pytest = "^3.0"
# pytest-cov = "^2.4"

# [tool.poetry.scripts]
# my-script = "my_package:main"