[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "equitable_assign"
version = "22.8.0"
authors = [
  { name="Shawheen Naderi", email="snaderi@csus.edu" },
  { name="Clark Fitzgerald", email="fitzgerald@csus.edu" },
]
description = "Generate random assignments of workers to tasks and balance each worker's load"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/clarkfitzg/equitable-assign"
"Bug Tracker" = "https://github.com/clarkfitzg/equitable-assign/issues"
