[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
authors = [
    { name="Eric DeMattos" }
]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyyaml",
]
description = "Configuration file parsing with argparse."
name = "cargparse"
readme = "README.md"
requires-python = ">=3.7"
version = "0.0.8"

[project.urls]
"Homepage" = "https://github.com/edemattos/cargparse"
"Bug Tracker" = "https://github.com/edemattos/cargparse/issues"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "darwin",
    "linux",
    "win32",
    "slow",
]
log_level = "INFO"
log_format = "%(asctime)s [%(levelname)s] %(message)s"
log_date_format = "%d %b %Y %H:%M:%S"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
mypy_path = "src/"
ignore_missing_imports = true
no_strict_optional = true
show_error_codes = true
namespace_packages = true
explicit_package_bases = true
