
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-01T10:07:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "89f22f8c125f9d397583ca9d2c1e80714601d5c8",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
