# coding: utf-8

"""
    external/v1/external_session_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""


import pprint
import re  # noqa: F401
from typing import TYPE_CHECKING

import six

from grid.openapi.configuration import Configuration

if TYPE_CHECKING:
    from datetime import datetime
    from grid.openapi.models import *

class Externalv1ScratchSpace(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mount_path': 'str',
        'size_gb': 'int'
    }

    attribute_map = {
        'mount_path': 'mountPath',
        'size_gb': 'sizeGb'
    }

    def __init__(self, mount_path: 'str' = None, size_gb: 'int' = None, _configuration=None):  # noqa: E501
        """Externalv1ScratchSpace - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._mount_path = None
        self._size_gb = None
        self.discriminator = None

        if mount_path is not None:
            self.mount_path = mount_path
        if size_gb is not None:
            self.size_gb = size_gb

    @property
    def mount_path(self) -> 'str':
        """Gets the mount_path of this Externalv1ScratchSpace.  # noqa: E501


        :return: The mount_path of this Externalv1ScratchSpace.  # noqa: E501
        :rtype: str
        """
        return self._mount_path

    @mount_path.setter
    def mount_path(self, mount_path: 'str'):
        """Sets the mount_path of this Externalv1ScratchSpace.


        :param mount_path: The mount_path of this Externalv1ScratchSpace.  # noqa: E501
        :type: str
        """

        self._mount_path = mount_path

    @property
    def size_gb(self) -> 'int':
        """Gets the size_gb of this Externalv1ScratchSpace.  # noqa: E501


        :return: The size_gb of this Externalv1ScratchSpace.  # noqa: E501
        :rtype: int
        """
        return self._size_gb

    @size_gb.setter
    def size_gb(self, size_gb: 'int'):
        """Sets the size_gb of this Externalv1ScratchSpace.


        :param size_gb: The size_gb of this Externalv1ScratchSpace.  # noqa: E501
        :type: int
        """

        self._size_gb = size_gb

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Externalv1ScratchSpace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'Externalv1ScratchSpace') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, Externalv1ScratchSpace):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: 'Externalv1ScratchSpace') -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, Externalv1ScratchSpace):
            return True

        return self.to_dict() != other.to_dict()
