# coding: utf-8

"""
    external/v1/external_session_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""


import pprint
import re  # noqa: F401
from typing import TYPE_CHECKING

import six

from grid.openapi.configuration import Configuration

if TYPE_CHECKING:
    from datetime import datetime
    from grid.openapi.models import *

class V1CreateSamlOrganizationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allowed_domains': 'list[str]',
        'name': 'str',
        'saml_metadata_url': 'str'
    }

    attribute_map = {
        'allowed_domains': 'allowedDomains',
        'name': 'name',
        'saml_metadata_url': 'samlMetadataUrl'
    }

    def __init__(self, allowed_domains: 'list[str]' = None, name: 'str' = None, saml_metadata_url: 'str' = None, _configuration=None):  # noqa: E501
        """V1CreateSamlOrganizationRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._allowed_domains = None
        self._name = None
        self._saml_metadata_url = None
        self.discriminator = None

        if allowed_domains is not None:
            self.allowed_domains = allowed_domains
        if name is not None:
            self.name = name
        if saml_metadata_url is not None:
            self.saml_metadata_url = saml_metadata_url

    @property
    def allowed_domains(self) -> 'list[str]':
        """Gets the allowed_domains of this V1CreateSamlOrganizationRequest.  # noqa: E501


        :return: The allowed_domains of this V1CreateSamlOrganizationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._allowed_domains

    @allowed_domains.setter
    def allowed_domains(self, allowed_domains: 'list[str]'):
        """Sets the allowed_domains of this V1CreateSamlOrganizationRequest.


        :param allowed_domains: The allowed_domains of this V1CreateSamlOrganizationRequest.  # noqa: E501
        :type: list[str]
        """

        self._allowed_domains = allowed_domains

    @property
    def name(self) -> 'str':
        """Gets the name of this V1CreateSamlOrganizationRequest.  # noqa: E501


        :return: The name of this V1CreateSamlOrganizationRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: 'str'):
        """Sets the name of this V1CreateSamlOrganizationRequest.


        :param name: The name of this V1CreateSamlOrganizationRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def saml_metadata_url(self) -> 'str':
        """Gets the saml_metadata_url of this V1CreateSamlOrganizationRequest.  # noqa: E501


        :return: The saml_metadata_url of this V1CreateSamlOrganizationRequest.  # noqa: E501
        :rtype: str
        """
        return self._saml_metadata_url

    @saml_metadata_url.setter
    def saml_metadata_url(self, saml_metadata_url: 'str'):
        """Sets the saml_metadata_url of this V1CreateSamlOrganizationRequest.


        :param saml_metadata_url: The saml_metadata_url of this V1CreateSamlOrganizationRequest.  # noqa: E501
        :type: str
        """

        self._saml_metadata_url = saml_metadata_url

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CreateSamlOrganizationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1CreateSamlOrganizationRequest') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CreateSamlOrganizationRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: 'V1CreateSamlOrganizationRequest') -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1CreateSamlOrganizationRequest):
            return True

        return self.to_dict() != other.to_dict()
