# coding: utf-8

"""
    external/v1/external_session_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""


import pprint
import re  # noqa: F401
from typing import TYPE_CHECKING

import six

from grid.openapi.configuration import Configuration

if TYPE_CHECKING:
    from datetime import datetime
    from grid.openapi.models import *

class V1ListCredentialsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'credentials': 'list[V1Credential]',
        'next_page_token': 'str',
        'previous_page_token': 'str',
        'total_size': 'str'
    }

    attribute_map = {
        'credentials': 'credentials',
        'next_page_token': 'nextPageToken',
        'previous_page_token': 'previousPageToken',
        'total_size': 'totalSize'
    }

    def __init__(self, credentials: 'list[V1Credential]' = None, next_page_token: 'str' = None, previous_page_token: 'str' = None, total_size: 'str' = None, _configuration=None):  # noqa: E501
        """V1ListCredentialsResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._credentials = None
        self._next_page_token = None
        self._previous_page_token = None
        self._total_size = None
        self.discriminator = None

        if credentials is not None:
            self.credentials = credentials
        if next_page_token is not None:
            self.next_page_token = next_page_token
        if previous_page_token is not None:
            self.previous_page_token = previous_page_token
        if total_size is not None:
            self.total_size = total_size

    @property
    def credentials(self) -> 'list[V1Credential]':
        """Gets the credentials of this V1ListCredentialsResponse.  # noqa: E501


        :return: The credentials of this V1ListCredentialsResponse.  # noqa: E501
        :rtype: list[V1Credential]
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials: 'list[V1Credential]'):
        """Sets the credentials of this V1ListCredentialsResponse.


        :param credentials: The credentials of this V1ListCredentialsResponse.  # noqa: E501
        :type: list[V1Credential]
        """

        self._credentials = credentials

    @property
    def next_page_token(self) -> 'str':
        """Gets the next_page_token of this V1ListCredentialsResponse.  # noqa: E501


        :return: The next_page_token of this V1ListCredentialsResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token: 'str'):
        """Sets the next_page_token of this V1ListCredentialsResponse.


        :param next_page_token: The next_page_token of this V1ListCredentialsResponse.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    @property
    def previous_page_token(self) -> 'str':
        """Gets the previous_page_token of this V1ListCredentialsResponse.  # noqa: E501


        :return: The previous_page_token of this V1ListCredentialsResponse.  # noqa: E501
        :rtype: str
        """
        return self._previous_page_token

    @previous_page_token.setter
    def previous_page_token(self, previous_page_token: 'str'):
        """Sets the previous_page_token of this V1ListCredentialsResponse.


        :param previous_page_token: The previous_page_token of this V1ListCredentialsResponse.  # noqa: E501
        :type: str
        """

        self._previous_page_token = previous_page_token

    @property
    def total_size(self) -> 'str':
        """Gets the total_size of this V1ListCredentialsResponse.  # noqa: E501


        :return: The total_size of this V1ListCredentialsResponse.  # noqa: E501
        :rtype: str
        """
        return self._total_size

    @total_size.setter
    def total_size(self, total_size: 'str'):
        """Sets the total_size of this V1ListCredentialsResponse.


        :param total_size: The total_size of this V1ListCredentialsResponse.  # noqa: E501
        :type: str
        """

        self._total_size = total_size

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ListCredentialsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ListCredentialsResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ListCredentialsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: 'V1ListCredentialsResponse') -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1ListCredentialsResponse):
            return True

        return self.to_dict() != other.to_dict()
