[project]
name = "Intaqt"
version = "0.0.4"
authors = [
  { name="Binary Ink Studio", email="contact@binaryinkstudio.com" },
]
description = "Status tracking API"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
dependencies = ['requests']
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://www.binaryinkstudio.com"
"Bug Tracker" = "https://www.binaryinkstudio.com"
