[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [  ".", "src", ]

[project]
name = "NYSECalendar"
version = "0.0.3"
authors = [
  { name="Masa Nakamura", email="masayang.mobile@gmail.com" },
]
description = "NYSE Calendar"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "python-dateutil"
]

[project.urls]
"Homepage" = "https://github.com/masayang/nysecalendar"
"Bug Tracker" = "https://github.com/masayang/nysecalendar/issues"


