[build-system]
requires = ["setuptools>=44.0.0", "wheel>=0.34.2", "Cython>=3.0a10", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "lzokay/version.py"