# pyproject.toml

[build-system]
requires      = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ybt-jira"
version = "1.0.0"
description = "TODO: add description"
readme = "README.md"
authors = [{ name = "y24 ved", email = "y24.ved@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
keywords = ["jira"]
dependencies = [
    "tomli",
    "jira",
    "rich",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest",
    "bumpver",
    "autopep8",
    "pip-tools",
]

[project.urls]
Homepage = "https://github.com/y24ved/ybt-jira"

[project.scripts]
realpython = "yjira.__main__:main"

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"README.md" = [
    "{version}",
]
"src/yjira/__init__.py" = [
    "{version}",
]
