# Generated by Django 3.2.4 on 2021-10-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reduction_viewer', '0012_remove_reductionrun_retry_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reductionrun',
            name='retry_when',
        ),
    ]
