[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas",
    "cobra"
]
build-backend = "setuptools.build_meta"

[project]
name = "sambaflux"
version = "0.1.1"
authors = [
  { name="Juliette Cooke", email="juliette.cooke@inrae.fr" },
]
description = "Sampling Biomarker Analysis using flux sampling"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]

[project.urls]
"Homepage" = "https://forgemia.inra.fr/metexplore/cbm/samba/-/tree/main/sambaflux"
"Bug Tracker" = "https://forgemia.inra.fr/metexplore/cbm/samba/-/issues"