UFs = {
    "RONDONIA": "RO",
    "RONDÔNIA": "RO",
    "ACRE": "AC",
    "AMAZONAS": "AM",
    "RORAIMA": "RR",
    "PARA": "PA",
    "PARÁ": "PA",
    "AMAPA": "AP",
    "AMAPÁ": "AP",
    "TOCANTINS": "TO",
    "MARANHAO": "MA",
    "MARANHÃO": "MA",
    "PIAUI": "PI",
    "PIAUÍ": "PI",
    "CEARA": "CE",
    "CEARÁ": "CE",
    "RIO GRANDE DO NORTE": "RN",
    "PARAIBA": "PB",
    "PARAÍBA": "PB",
    "PERNAMBUCO": "PE",
    "ALAGOAS": "AL",
    "SERGIPE": "SE",
    "BAHIA": "BA",
    "MINAS GERAIS": "MG",
    "ESPIRITO SANTO": "ES",
    "ESPÍRITO SANTO": "ES",
    "RIO DE JANEIRO": "RJ",
    "SÃO PAULO": "SP",
    "SAO PAULO": "SP",
    "PARANA": "PR",
    "PARANÁ": "PR",
    "SANTA CATARINA": "SC",
    "RIO GRANDE DO SUL": "RS",
    "MATO GROSSO DO SUL": "MS",
    "MATO GROSSO": "MT",
    "GOIAS": "GO",
    "GOIÁS": "GO",
    "DISTRITO FEDERAL": "DF",
}

UF_TO_ESTADOS = {
    "AC": "ACRE",
    'AM': 'AMAZONAS',
    'AL': 'ALAGOAS',
    'AP': 'AMAPÁ',
    'BA': 'BAHIA',
    'CE': 'CEARÁ',
    'DF': 'DISTRITO FEDERAL',
    'ES': 'ESPÍRITO SANTO',
    'GO': 'GOIÁS',
    'MA': 'MARANHÃO',
    'MT': 'MATO GROSSO',
    'MS': 'MATO GROSSO DO SUL',
    'MG': 'MINAS GERAIS',
    'PA': 'PARÁ',
    'PB': 'PARAÍBA',
    'PR': 'PARANÁ',
    'PE': 'PERNAMBUCO',
    'PI': 'PIAUÍ',
    'RJ': 'RIO DE JANEIRO',
    'RN': 'RIO GRANDE DO NORTE',
    'RS': 'RIO GRANDE DO SUL',
    'RO': 'RONDÔNIA',
    'RR': 'RORAIMA',
    'SC': 'SANTA CATARINA',
    'SP': 'SÃO PAULO',
    'SE': 'SERGIPE',
    'TO': 'TOCANTINS',
}

UF_TO_REGIAO = {
    "DF": "CENTRO-OESTE",
    "GO": "CENTRO-OESTE",
    "MS": "CENTRO-OESTE",
    "MT": "CENTRO-OESTE",
    "AL": "NORDESTE",
    "BA": "NORDESTE",
    "CE": "NORDESTE",
    "MA": "NORDESTE",
    "PB": "NORDESTE",
    "PE": "NORDESTE",
    "PI": "NORDESTE",
    "RN": "NORDESTE",
    "SE": "NORDESTE",
    "TO": "NORTE",
    "AC": "NORTE",
    "AM": "NORTE",
    "AP": "NORTE",
    "PA": "NORTE",
    "RO": "NORTE",
    "RR": "NORTE",
    "ES": "SUDESTE",
    "MG": "SUDESTE",
    "RJ": "SUDESTE",
    "SP": "SUDESTE",
    "PR": "SUL",
    "RS": "SUL",
    "SC": "SUL",
    'BR': "BRASIL"
}

CLUSTER_BAIN = {
    "AC": "Manaus",
    'AM': 'Manaus',
    'AL': 'Pernambuco',
    'AP': 'Belém',
    'BA': 'RLAM',
    'CE': 'Ceará',
    'DF': 'Centro Oeste',
    'ES': 'RJ/ES',
    'GO': 'Centro Oeste',
    'MA': 'MAPITO',
    'MT': 'Centro Oeste',
    'MS': 'Centro Oeste',
    'MG': 'MG',
    'PA': 'Belém',
    'PB': 'Pernambuco',
    'PR': 'REPAR',
    'PE': 'Pernambuco',
    'PI': 'MAPITO',
    'RJ': 'RJ/ES',
    'RN': 'Ceará',
    'RS': 'REFAP',
    'RO': 'Manaus',
    'RR': 'Manaus',
    'SC': 'REPAR',
    'SP': 'SP',
    'SE': 'RLAM',
    'TO': 'MAPITO',
}

REGIAO_DICT = {
    "CO": 'CENTRO-OESTE',
    "S": 'SUL',
    "SE": 'SUDESTE',
    "N": 'NORTE',
    "NE": 'NORDESTE'
}
