[build-system]
requires = ["setuptools", "tree_sitter", "tree_sitter_type_provider"]
build-backend = "setuptools.build_meta"

[pytest]
testpaths = "test"

[tool.pytest.ini_options]
enable_assertion_pass_hook = true
filterwarnings = ["ignore::DeprecationWarning:.*:"]
addopts = "--ignore=test/data"

[tool.bumpver]
current_version = "1.5.21"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"']
"setup.py" = ['version="{version}"']
"doc-source/conf.py" = ['release = "{version}"']
