
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T16:01:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec2d837fd94c50c7f50f8752ec5fbf966d73921e",
 "version": "2022.7.29.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
