
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-02T18:57:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad985ce1c2e9e6a0824654b97116dcd0fc7ae39f",
 "version": "v22.08.00a220804"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
