[tool.poetry]
name = "isocodes"
version = "2022.08.02"
description = "This project provides lists of various ISO standards (e.g. country, language, language scripts, and currency names) in one place"
authors = ["Atem18 <contact@atemlire.io>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Atem18/isocodes"
repository = "https://github.com/Atem18/isocodes"
keywords = ["iso"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
mkdocs = "^1.2.2"
mkdocs-material = "^8.0.0"
mkdocstrings = "^0.19.0"
black = "^21.9b0"
tox = "^3.24.5"
mypy = "^0.971"
flake8 = "^5.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
