[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
[project]
name = 'dervin'
version = '0.0.1'
authors = [{name="João Rocha", email="rocha.jmiguel@gmail.com"}]
description = 'Engine that implements strategies to mitigate the phase ordering problem'
readme = 'README.md'
requires-python = '>=3.7'
[project.scripts]
dervin = 'dervin.app:run'
