[tool.poetry]
name = "fear_data"
version = "0.1.0"
description = "Python package for data analysis collected from Med-Associates VideoFreeze software."
authors = ["kpuhger <krpuhger@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
seaborn = "^0.11.2"
matplotlib = "^3.5.2"
pandas = "^1.4.3"
numpy = "^1.23.1"
pingouin = "^0.5.2"
scipy = "^1.8.1"
"ruamel.yaml" = "^0.17.21"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
pytest = "^7.1.2"
pylint = "^2.14.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
