# BUILD


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


# TOOLS

## Pytest & Plugins

[tool.pytest.ini_options]
minversion = "6.2"
addopts = "--strict-markers"
markers = [
    "slow: Marks a slow test",
    "integration: Tests applicable to a newly Generated Project, running with tox",
    "network_bound: Require internet connection",
]
testpaths = [
    "tests",
]


## Black formatting/linting

[tool.black]
line-length = 95
include = '\.pyi?$'
extend-exclude = '''
# A regex preceeded with ^/ will apply only to files and directories
# in the root of the project.
# ^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
tests/smoke_test.py|
hooks/post_gen_project.py
'''


[tool.isort]
profile = 'black'


[tool.software-release]
version_variable = "src/pytest_object_getter/__init__.py:__version__"
