[tool.poetry]
name = "AEngine"
version = "1.0.1"
description = "Console applications Engine"
authors = ["alex"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
