[tool.poetry]
name = "run-logger"
version = "0.1.8"
description = "A utility for logging runs."
readme = "README.md"
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]
maintainers = ["Ethan Brooks <ethanabrooks@gmail.com>"]
include = ["run_logger/py.typed"]
repository = "https://github.com/run-tracker/run-logger"
homepage = "https://run-logger.readthedocs.io/en/latest/index.html"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0"
numpy = "^1.21.5"
gql = "^3.1.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
ipdb = "^0.13.9"
ipython = "^7.25.0"
Sphinx = "^4.5.0"
myst-parser = "^0.17.0"
sphinx-book-theme = "^0.3.2"
sphinx-copybutton = "^0.5.0"
sphinx-autobuild = "^2021.3.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
