[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cs-commons"
authors = [{name = "Anders Petersson", email = "petersson@chillservices.com"}]
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "description"]

[project.urls]
Home = "https://chillservices.com/"

[tool.flit.module]
name = "cs_commons"
