[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "preservedfs"
version = "0.1.5"
authors = [
  { name="KirmTwinty", email="thibaud.toullier@inria.fr" },
]
description = "A FileSystem that preserves original files."
dependencies=[
	"fuse-python",
	"click"
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=2.5"
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.scripts]
preservedfs = "preservedfs.cli:main"

[project.urls]
"Homepage" = "https://gitlab.com/KirmTwinty/preserved-fs"
"Bug Tracker" = "https://gitlab.com/KirmTwinty/preserved-fs/issues"