[tool.poetry]
name = "wa2rasa"
version = "0.1.0"
description = "Convert Watson Assistant skill object to rasa nlu.yml file."
authors = ["Cloves Paiva <clovesgtx@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.6.1"
rich = "^12.5.1"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.6.0"
radon = "^5.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wa2rasa = 'wa2rasa.cli:app'
