
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T16:04:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5640b2b23b51e76a93911fa88e6c1a3de91d538f",
 "version": "2.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
