[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CrashResolver"
authors = [{name = "cosmore", email = "icosmore@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

dependencies = [
    "requests>=2.28.0",
    "PyYAML>=6.0"
]

[project.urls]
Documentation = "https://github.com/beyonddoor/CrashResolver/"
Source = "https://github.com/beyonddoor/CrashResolver/"