[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "vivqu"
version = "0.0.1"
authors = [
    { name="Ding Yang", email="yangding19thu@outlook.com" },
]
description = "Simplified interface and visualization for data unit test based on pydeequ"
readme = "README.md"
license = { file="LICENSE" }

requires-python = ">=3.6.2"
# install_requires=[
#     'pydeequ==1.0.1',
# ]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]


[project.urls]
"Homepage" = "https://gitlab.awx.im/awx-platform/ml-platform/risk-data-quality-check/"
"Bug Tracker" = "https://gitlab.awx.im/awx-platform/ml-platform/risk-data-quality-check/-/issues"