[tool.poetry]
name = "pypy-geoff"
version = "0.1.0"
description = ""
authors = ["Geoff Dutton <g.dutton@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.20.0"
black = {version = "^22.6.0", allow-prereleases = true}
scriv = {extras = ["toml"], version = "^0.16.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
