[tool.poetry]
name = "otlet-cli"
version = "1.0.1"
description = "CLI interface for otlet, the PyPI Web API wrapper"
readme = "README.md"
authors = ["Noah Tanner (nhtnr) <noahtnr@gmail.com>"]
repository = "https://github.com/nhtnr/otlet-cli"
license = "MIT"
classifiers = ["Development Status :: 5 - Production/Stable",  "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3 :: Only"]

[tool.poetry.dependencies]
python = "^3.7"
otlet = "^1.0.0"
arrow = "^1.2.2"

[tool.poetry.scripts]
otlet = "otlet_cli.cli:run_cli"

[tool.poetry.dev-dependencies]
pylint = "~=2.13.9"
black = "^22.6.0"
radon = "^5.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
