
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-02T11:08:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bfbd66e8a1e9ecf679669ad50c9cb84e07b8015",
 "version": "2.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
