
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-02T15:00:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d37b40dc84b82e1602b470b407fd8e135b5d09cb",
 "version": "0.2.17.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
