[tool.poetry]
name = "amocrm_client"
version = "0.2.0"
description = ""
authors = ["BB Team"]

[tool.poetry.dependencies]
python = "^3.9"
grequests = "^0.6.0"
aiohttp = "3.7.4"

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
