# Generated by Django 2.2.16 on 2020-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user_feedback", "0002_auto_20200912_2239")]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="archived",
            field=models.BooleanField(default=False),
        )
    ]
