[tool.poetry]
name = "graph_partition"
version = "0.1.16"
description = "Graph Partitioning Algorithms"
license = "MIT"
readme = "README.md"
authors = ["somsubhra88"]
keywords = ["Graph Convolutional Network", "Clustering", "Spectral Clustering", "Graph Neural Network"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
torch = "1.12.0"
numpy = "1.23.1"
scikit-learn = "1.1.1"
k-means-constrained = "0.7.1"
scipy = "^1.8.1"

[tool.poetry.dev-dependencies]
black = {version = "^22.6.0", python = ">=3.9,<3.11"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
