[tool.poetry]
name = "translator-template"
version = "0.2.4"
license = "MIT"
description = "Utility for generating a Microsoft Word file from a simple document description, for translators."
readme = "README.md"
authors = ["Chris Thrasher <cthrash@github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pylint = "^2.8.3"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
rope = "^0.19.0"
flake8 = "^3.9.2"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate = 'translator_template.app:main'