
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-26T14:41:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6357396a6be8edce7bde224c761f3bd5d2c499f0",
 "version": "v22.10.00a220729"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
