LOCK_CODES = [
    {
        "river_code": "AL",
        "river_name": "ALABAMA-COOSA RIVERS",
        "lock_no": "11",
        "lock_name": "CLAIBORNE LOCK AND DAM",
    },
    {
        "river_code": "AL",
        "river_name": "ALABAMA-COOSA RIVERS",
        "lock_no": "12",
        "lock_name": "MILLERS FERRY LOCK AND DAM",
    },
    {
        "river_code": "AL",
        "river_name": "ALABAMA-COOSA RIVERS",
        "lock_no": "13",
        "lock_name": "ROBERT F. HENRY LOCK AND DAM",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "43",
        "lock_name": "C.W. BILL YOUNG LOCK AND DAM",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "42",
        "lock_name": "LOCK AND DAM 2",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "44",
        "lock_name": "LOCK AND DAM 4",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "45",
        "lock_name": "LOCK AND DAM 5",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "46",
        "lock_name": "LOCK AND DAM 6",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "47",
        "lock_name": "LOCK AND DAM 7",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "48",
        "lock_name": "LOCK AND DAM 8",
    },
    {
        "river_code": "AG",
        "river_name": "ALLEGHENY RIVER",
        "lock_no": "49",
        "lock_name": "LOCK AND DAM 9",
    },
    {
        "river_code": "AP",
        "river_name": "APLCHCLA/CHATTAHO/FLINT RIVERS",
        "lock_no": "22",
        "lock_name": "GEORGE W ANDREWS LOCK AND DAM",
    },
    {
        "river_code": "AP",
        "river_name": "APLCHCLA/CHATTAHO/FLINT RIVERS",
        "lock_no": "21",
        "lock_name": "JIM WOODRUFF LOCK AND DAM",
    },
    {
        "river_code": "AP",
        "river_name": "APLCHCLA/CHATTAHO/FLINT RIVERS",
        "lock_no": "23",
        "lock_name": "WALTER F GEORGE LOCK AND DAM",
    },
    {
        "river_code": "AT",
        "river_name": "ATCHAFALAYA RIVER",
        "lock_no": "11",
        "lock_name": "BERWICK LOCK",
    },
    {
        "river_code": "AI",
        "river_name": "ATLANTIC INTRACOASTAL WATERWAY",
        "lock_no": "11",
        "lock_name": "GREAT BRIDGE GUARD LOCK",
    },
    {
        "river_code": "BT",
        "river_name": "BAYOU TECHE",
        "lock_no": "31",
        "lock_name": "KEYSTONE LOCK",
    },
    {
        "river_code": "BR",
        "river_name": "BLACK ROCK CH/TONAWANDA HARBOR",
        "lock_no": "01",
        "lock_name": "BLACK ROCK LOCK",
    },
    {
        "river_code": "BW",
        "river_name": "BLACKWARRIOR/TOMBIGBEE RIVERS",
        "lock_no": "03",
        "lock_name": "ARMSTD I. SELDEN LOCK AND DAM",
    },
    {
        "river_code": "BW",
        "river_name": "BLACKWARRIOR/TOMBIGBEE RIVERS",
        "lock_no": "01",
        "lock_name": "COFFEEVILLE LOCK",
    },
    {
        "river_code": "BW",
        "river_name": "BLACKWARRIOR/TOMBIGBEE RIVERS",
        "lock_no": "02",
        "lock_name": "DEMOPOLIS LOCK AND DAM",
    },
    {
        "river_code": "BW",
        "river_name": "BLACKWARRIOR/TOMBIGBEE RIVERS",
        "lock_no": "05",
        "lock_name": "HOLT LOCK AND DAM",
    },
    {
        "river_code": "BW",
        "river_name": "BLACKWARRIOR/TOMBIGBEE RIVERS",
        "lock_no": "06",
        "lock_name": "JOHN HOLLIS BANKHEAD LK AND DM",
    },
    {
        "river_code": "BW",
        "river_name": "BLACKWARRIOR/TOMBIGBEE RIVERS",
        "lock_no": "04",
        "lock_name": "WILLIAM BACON OLIVER LK AND DM",
    },
    {
        "river_code": "CA",
        "river_name": "CALCASIEU RIVER",
        "lock_no": "23",
        "lock_name": "CALCASIEU SALT WATER BARRIER",
    },
    {
        "river_code": "CN",
        "river_name": "CANAVERAL HARBOR",
        "lock_no": "21",
        "lock_name": "CANAVERAL LOCK",
    },
    {
        "river_code": "FR",
        "river_name": "CAPE FEAR RIVER",
        "lock_no": "01",
        "lock_name": "LOCK AND DAM 1",
    },
    {
        "river_code": "FR",
        "river_name": "CAPE FEAR RIVER",
        "lock_no": "02",
        "lock_name": "LOCK AND DAM 2",
    },
    {
        "river_code": "FR",
        "river_name": "CAPE FEAR RIVER",
        "lock_no": "03",
        "lock_name": "WILLIAM O HUSKE LOCK AND DAM",
    },
    {
        "river_code": "CH",
        "river_name": "CHICAGO RIVER",
        "lock_no": "01",
        "lock_name": "CHICAGO LOCK",
    },
    {
        "river_code": "CI",
        "river_name": "CLINCH RIVER",
        "lock_no": "11",
        "lock_name": "MELTON HILL LOCK",
    },
    {
        "river_code": "CO",
        "river_name": "COLUMBIA RIVER",
        "lock_no": "01",
        "lock_name": "BONNEVILLE LOCK AND DAM",
    },
    {
        "river_code": "CO",
        "river_name": "COLUMBIA RIVER",
        "lock_no": "03",
        "lock_name": "JOHN DAY LOCK AND DAM",
    },
    {
        "river_code": "CO",
        "river_name": "COLUMBIA RIVER",
        "lock_no": "24",
        "lock_name": "MCNARY LOCK AND DAM",
    },
    {
        "river_code": "CO",
        "river_name": "COLUMBIA RIVER",
        "lock_no": "02",
        "lock_name": "THE DALLES DAM",
    },
    {
        "river_code": "CU",
        "river_name": "CUMBERLAND RIVER",
        "lock_no": "21",
        "lock_name": "BARKLEY LOCK",
    },
    {
        "river_code": "CU",
        "river_name": "CUMBERLAND RIVER",
        "lock_no": "22",
        "lock_name": "CHEATHAM LOCK",
    },
    {
        "river_code": "CU",
        "river_name": "CUMBERLAND RIVER",
        "lock_no": "23",
        "lock_name": "CORDELL HULL LOCK",
    },
    {
        "river_code": "CU",
        "river_name": "CUMBERLAND RIVER",
        "lock_no": "24",
        "lock_name": "OLD HICKORY LOCK",
    },
    {
        "river_code": "DS",
        "river_name": "DISMAL SWAMP CANAL ROUTE",
        "lock_no": "01",
        "lock_name": "DEEP CREEK LOCK",
    },
    {
        "river_code": "DS",
        "river_name": "DISMAL SWAMP CANAL ROUTE",
        "lock_no": "02",
        "lock_name": "SOUTH MILLS LOCK",
    },
    {
        "river_code": "FB",
        "river_name": "FRESHWATER BAYOU",
        "lock_no": "41",
        "lock_name": "FRESHWATER BAYOU LOCK",
    },
    {
        "river_code": "GB",
        "river_name": "GREEN & BARREN RIVERS",
        "lock_no": "21",
        "lock_name": "LOCK AND DAM 1",
    },
    {
        "river_code": "GB",
        "river_name": "GREEN & BARREN RIVERS",
        "lock_no": "22",
        "lock_name": "LOCK AND DAM 2",
    },
    {
        "river_code": "GB",
        "river_name": "GREEN & BARREN RIVERS",
        "lock_no": "23",
        "lock_name": "LOCK AND DAM 3",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "04",
        "lock_name": "ALGIERS LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "06",
        "lock_name": "BAYOU BOEUF LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "02",
        "lock_name": "BAYOU SORREL LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "13",
        "lock_name": "BRAZOS EAST GATE",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "14",
        "lock_name": "BRAZOS WEST GATE",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "08",
        "lock_name": "CALCASIEU LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "22",
        "lock_name": "CATFISH POINT CONTROL STRUCT",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "11",
        "lock_name": "COLORADO RIVER EAST LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "12",
        "lock_name": "COLORADO RIVER WEST LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "05",
        "lock_name": "HARVEY LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "03",
        "lock_name": "INNER HRBR NAVIGATION CANL LK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "77",
        "lock_name": "LELAND BOWMAN LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "01",
        "lock_name": "PORT ALLEN LOCK",
    },
    {
        "river_code": "GI",
        "river_name": "GULF INTRACOASTAL WATERWAY",
        "lock_no": "21",
        "lock_name": "SCHOONER BAYOU CONTROL STRUCT",
    },
    {
        "river_code": "HU",
        "river_name": "HUDSON RIVER",
        "lock_no": "01",
        "lock_name": "TROY LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "03",
        "lock_name": "BRANDON ROAD LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "04",
        "lock_name": "DRESDEN ISLAND LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "08",
        "lock_name": "LAGRANGE LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "02",
        "lock_name": "LOCKPORT LOCK",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "05",
        "lock_name": "MARSEILLES LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "07",
        "lock_name": "PEORIA LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "06",
        "lock_name": "STARVED ROCK LOCK AND DAM",
    },
    {
        "river_code": "IL",
        "river_name": "ILLINOIS WATERWAY",
        "lock_no": "01",
        "lock_name": "THOMAS J. O'BRIEN LOCK",
    },
    {
        "river_code": "KA",
        "river_name": "KANAWHA RIVER",
        "lock_no": "03",
        "lock_name": "LONDON LOCKS AND DAM MAIN 1",
    },
    {
        "river_code": "KA",
        "river_name": "KANAWHA RIVER",
        "lock_no": "02",
        "lock_name": "MARMET LOCKS AND DAM MAIN 1",
    },
    {
        "river_code": "KA",
        "river_name": "KANAWHA RIVER",
        "lock_no": "01",
        "lock_name": "WINFIELD LOCKS AND DAM MAIN 1",
    },
    {
        "river_code": "KS",
        "river_name": "KASKASKIA RIVER",
        "lock_no": "01",
        "lock_name": "KASKASKIA RIVER NAVAGATION LK",
    },
    {
        "river_code": "WS",
        "river_name": "LAKE WASHINGTON SHIP CANAL",
        "lock_no": "01",
        "lock_name": "HIRAM M CHITTENDEN LOCKS",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "09",
        "lock_name": "ARTHUR V ORMOND L AND D",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "24",
        "lock_name": "CHOUTEAU LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "05",
        "lock_name": "COL CHARLES D MAYNARD",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "10",
        "lock_name": "DARDANELLE LK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "06",
        "lock_name": "DAVID D TERRY LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "04",
        "lock_name": "EMMETT SANDERS LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "13",
        "lock_name": "JAMES W. TRIMBLE LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "03",
        "lock_name": "JOE HARDIN LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "99",
        "lock_name": "MONTGOMERY POINT LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "07",
        "lock_name": "MURRAY LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "25",
        "lock_name": "NEWT GRAHAM LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "01",
        "lock_name": "NORRELL LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "11",
        "lock_name": "OZARK LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "22",
        "lock_name": "RBRT S KERR LK AND DAM AND RES",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "08",
        "lock_name": "TOAD SUCK FERRY LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "21",
        "lock_name": "W D MAYO LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "23",
        "lock_name": "WEBBERS FALLS LOCK AND DAM",
    },
    {
        "river_code": "MK",
        "river_name": "MC-KERR ARKANSAS RIV NAV SYS",
        "lock_no": "02",
        "lock_name": "WILBUR D MILLS LOCK AND DAM",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "27",
        "lock_name": "CHAIN OF ROCKS LOCK AND DAM 27",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "19",
        "lock_name": "LOCK 19",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "01",
        "lock_name": "LOCK AND DAM 1",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "10",
        "lock_name": "LOCK AND DAM 10",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "11",
        "lock_name": "LOCK AND DAM 11",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "12",
        "lock_name": "LOCK AND DAM 12",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "13",
        "lock_name": "LOCK AND DAM 13",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "14",
        "lock_name": "LOCK AND DAM 14",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "15",
        "lock_name": "LOCK AND DAM 15",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "16",
        "lock_name": "LOCK AND DAM 16",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "17",
        "lock_name": "LOCK AND DAM 17",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "18",
        "lock_name": "LOCK AND DAM 18",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "02",
        "lock_name": "LOCK AND DAM 2",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "20",
        "lock_name": "LOCK AND DAM 20",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "21",
        "lock_name": "LOCK AND DAM 21",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "22",
        "lock_name": "LOCK AND DAM 22",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "24",
        "lock_name": "LOCK AND DAM 24",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "25",
        "lock_name": "LOCK AND DAM 25",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "03",
        "lock_name": "LOCK AND DAM 3",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "04",
        "lock_name": "LOCK AND DAM 4",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "05",
        "lock_name": "LOCK AND DAM 5",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "55",
        "lock_name": "LOCK AND DAM 5A",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "06",
        "lock_name": "LOCK AND DAM 6",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "07",
        "lock_name": "LOCK AND DAM 7",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "08",
        "lock_name": "LOCK AND DAM 8",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "09",
        "lock_name": "LOCK AND DAM 9",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "26",
        "lock_name": "MEL PRICE LOCK AND DAM",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "52",
        "lock_name": "ST ANTHONY FALLS - LOWER LOCK",
    },
    {
        "river_code": "MI",
        "river_name": "MISSISSIPPI RIVER",
        "lock_no": "51",
        "lock_name": "ST ANTHONY FALLS - UPPER LOCK",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "26",
        "lock_name": "GRAYS LANDING LOCK AND DAM",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "30",
        "lock_name": "HILDEBRAND LOCK AND DAM",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "22",
        "lock_name": "LOCK AND DAM 2",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "23",
        "lock_name": "LOCK AND DAM 3",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "24",
        "lock_name": "LOCK AND DAM 4",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "25",
        "lock_name": "MAXWELL LOCK AND DAM",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "29",
        "lock_name": "MORGANTOWN LOCK AND DAM",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "31",
        "lock_name": "OPEKISKA LOCK AND DAM",
    },
    {
        "river_code": "MN",
        "river_name": "MONONGAHELA RIVER",
        "lock_no": "28",
        "lock_name": "POINT MARION LOCK AND DAM",
    },
    {
        "river_code": "00",
        "river_name": "NONE",
        "lock_no": "00",
        "lock_name": "NONE",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "21",
        "lock_name": "BELLEVILLE LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "75",
        "lock_name": "CANNELTON LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "25",
        "lock_name": "CAPT ANT MELDAHL LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "02",
        "lock_name": "DASHIELDS LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "01",
        "lock_name": "EMSWORTH LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "24",
        "lock_name": "GREENUP LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "71",
        "lock_name": "HANNIBAL LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "77",
        "lock_name": "JOHN T. MYERS LOCK & DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "52",
        "lock_name": "LOCK AND DAM 52",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "53",
        "lock_name": "LOCK AND DAM 53",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "41",
        "lock_name": "MARKLAND LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "42",
        "lock_name": "MCALPINE LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "03",
        "lock_name": "MONTGOMERY LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "04",
        "lock_name": "NEW CUMBERLAND LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "76",
        "lock_name": "NEWBURGH LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "79",
        "lock_name": "OLMSTED LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "05",
        "lock_name": "PIKE ISLAND LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "22",
        "lock_name": "RACINE LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "26",
        "lock_name": "ROBERT C. BYRD LOCKS AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "78",
        "lock_name": "SMITHLAND LOCK AND DAM",
    },
    {
        "river_code": "OH",
        "river_name": "OHIO RIVER",
        "lock_no": "72",
        "lock_name": "WILLOW ISLAND LOCKS AND DAM",
    },
    {
        "river_code": "OK",
        "river_name": "OKEECHOBEE WATERWAY",
        "lock_no": "02",
        "lock_name": "MOORE HAVEN LOCK",
    },
    {
        "river_code": "OK",
        "river_name": "OKEECHOBEE WATERWAY",
        "lock_no": "03",
        "lock_name": "ORTONA LOCK AND DAM",
    },
    {
        "river_code": "OK",
        "river_name": "OKEECHOBEE WATERWAY",
        "lock_no": "05",
        "lock_name": "PORT MAYACA LOCK",
    },
    {
        "river_code": "OK",
        "river_name": "OKEECHOBEE WATERWAY",
        "lock_no": "01",
        "lock_name": "ST LUCIE LOCK AND DAM",
    },
    {
        "river_code": "OK",
        "river_name": "OKEECHOBEE WATERWAY",
        "lock_no": "04",
        "lock_name": "W P FRKLIN LCK AND CTRL STRCT",
    },
    {
        "river_code": "OD",
        "river_name": "OLD RIVER",
        "lock_no": "51",
        "lock_name": "OLD RIVER LOCK",
    },
    {
        "river_code": "OB",
        "river_name": "OUACHITA and BLACK RIVERS",
        "lock_no": "02",
        "lock_name": "COLUMBIA LOCK AND DAM",
    },
    {
        "river_code": "OB",
        "river_name": "OUACHITA and BLACK RIVERS",
        "lock_no": "03",
        "lock_name": "FELSENTHAL LOCK AND DAM",
    },
    {
        "river_code": "OB",
        "river_name": "OUACHITA and BLACK RIVERS",
        "lock_no": "01",
        "lock_name": "JONESVILLE LOCK AND DAM",
    },
    {
        "river_code": "OB",
        "river_name": "OUACHITA and BLACK RIVERS",
        "lock_no": "04",
        "lock_name": "THATCHER LOCK AND DAM",
    },
    {
        "river_code": "RR",
        "river_name": "RED RIVER",
        "lock_no": "45",
        "lock_name": "JOE D. WAGGONNER JR LOCK",
    },
    {
        "river_code": "RR",
        "river_name": "RED RIVER",
        "lock_no": "42",
        "lock_name": "JOHN H. OVERTON",
    },
    {
        "river_code": "RR",
        "river_name": "RED RIVER",
        "lock_no": "41",
        "lock_name": "LINDY CLAIBORNE BOGGS LOCK",
    },
    {
        "river_code": "RR",
        "river_name": "RED RIVER",
        "lock_no": "43",
        "lock_name": "LOCK AND DAM 3",
    },
    {
        "river_code": "RR",
        "river_name": "RED RIVER",
        "lock_no": "44",
        "lock_name": "RUSSELL B. LONG",
    },
    {
        "river_code": "SN",
        "river_name": "SNAKE RIVER",
        "lock_no": "01",
        "lock_name": "ICE HARBOR LOCK AND DAM",
    },
    {
        "river_code": "SN",
        "river_name": "SNAKE RIVER",
        "lock_no": "03",
        "lock_name": "LITTLE GOOSE LOCK AND DAM",
    },
    {
        "river_code": "SN",
        "river_name": "SNAKE RIVER",
        "lock_no": "04",
        "lock_name": "LOWER GRANITE LOCK AND DAM",
    },
    {
        "river_code": "SN",
        "river_name": "SNAKE RIVER",
        "lock_no": "02",
        "lock_name": "LOWER MONUMENTAL LOCK AND DAM",
    },
    {
        "river_code": "SM",
        "river_name": "ST. MARYS RIVER",
        "lock_no": "01",
        "lock_name": "ST. MARYS LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "07",
        "lock_name": "CHICKAMAUGA LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "09",
        "lock_name": "FORT LOUDOUN LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "04",
        "lock_name": "GEN JOS WHEELER LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "05",
        "lock_name": "GUNTERSVILLE LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "01",
        "lock_name": "KENTUCKY LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "06",
        "lock_name": "NICKAJAC LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "02",
        "lock_name": "PICKWICK LANDING LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "08",
        "lock_name": "WATTS BAR LOCK",
    },
    {
        "river_code": "TN",
        "river_name": "TENNESSEE RIVER",
        "lock_no": "03",
        "lock_name": "WILSON LOCK",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "44",
        "lock_name": "ABERDEEN LOCK AND DAM",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "45",
        "lock_name": "AMORY LOCK",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "47",
        "lock_name": "FULTON LOCK",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "49",
        "lock_name": "G.V. SONNY MONTGOMERY LOCK",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "46",
        "lock_name": "GLOVER WILKINS LOCK",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "41",
        "lock_name": "HOWELL HEFLIN LOCK AND DAM",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "50",
        "lock_name": "JAMIE WHITTEN LOCK AND DAM",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "43",
        "lock_name": "JOHN C. STENNIS LOCK AND DAM",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "48",
        "lock_name": "JOHN RANKIN LOCK",
    },
    {
        "river_code": "TT",
        "river_name": "TENNESSEE TOMBIGBEE WATERWAY",
        "lock_no": "42",
        "lock_name": "TOM BEVILL LOCK AND DAM",
    },
    {
        "river_code": "IN",
        "river_name": "THE INLAND ROUTE",
        "lock_no": "61",
        "lock_name": "ALANSON LOCK",
    },
    {
        "river_code": "WI",
        "river_name": "WILLAMETTE RIVER",
        "lock_no": "15",
        "lock_name": "WILLAMETTE FALLS GUARD LOCK",
    },
    {
        "river_code": "WI",
        "river_name": "WILLAMETTE RIVER",
        "lock_no": "11",
        "lock_name": "WILLAMETTE FALLS LOCKS 1 - 4",
    }
]