[tool.poetry]
name = "pygarn"
version = "0.2.0"
description = ""
authors = [
    "Julian Stier <julian.stier@uni-passau.de>"
]
license = "MIT"

include = [
    "pyproject.toml",
    "README.md"
]
exclude = [
    "res/*.graphml"
]
readme = "README.md"

homepage = "https://github.com/innvariant/pygarn"
repository = "https://github.com/innvariant/pygarn"

keywords = ["graph operations", "networkx extension", "graph assembly", "graph construction sequence", "graph evolution"]

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.7.1"


[tool.poetry.dev-dependencies]
black = "^22.3.0"
pre-commit = "^2.3.0"
pytest = "^3.0"
mkdocs = "^1.1.2"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"

[tool.isort]
profile = "black"
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
filter_files = true
src_paths = ["pygarn", "tests"]
skip_glob = ["*/setup.py", "res/", "examples/"]
known_first_party = "pygarn"
known_third_party = ["pytest"]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | res
  | build
  | dist
  | tests/cache/
  | tests/.*/setup.py
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
