
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-01T21:52:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c10468dd32ed50b9a9d5f6fd06f051238f08b58",
 "version": "0.2.17.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
