
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T11:31:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "29e012d1267b00419edd43926bd4f1b5f5b84952",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
