[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
[project]
name = 'ghopper'
version = '0.0.2'
authors = [{name="João Rocha"}]
description = 'This is a placeholder for the package ghopper. This package implements a framework that evaluates strategies to mitigate the phase ordering problem.'
readme = 'README.md'
requires-python = '>=3.7'
[project.scripts]
ghopper = 'ghopper.app:run'
