[tool.poetry]
name = "provworkflow"
version = "0.1.1"
description = "A Python library for creating Workflows containing Blocks that log their actions according to a specialisation of the PROV-O standard."
authors = ["nicholascar <nicholas.car@surroundaustralia.com>"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    # Pick your license as you wish
    # 'License :: OSI Approved :: MIT License', -- not licensed
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
keywords = ["workflow", "provenance", "semantic"]

[[tool.poetry.source]]
name = "provworkflow"
url = "https://github.com/surroundaustralia/provwf"

[tool.poetry.dependencies]
python = "^3.9"
rdflib = "^6.1.1"
requests = "^2.27.1"
GitPython = "^3.1.27"

[tool.poetry.dev-dependencies]
codespell = "^2.1.0"
black = "^22.3.0"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
