_target_: nlhappy.datamodules.TextClassificationDataModule
dataset_dir: ${dataset_dir} 
plm_dir: ${plm_dir}

dataset: 
plm: chinese-roberta-wwm-ext
max_length: 
batch_size: 
num_workers: 0
pin_memory: False


