
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T12:56:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbdb8f5a4dcd7202d92763a350424e4b0806de36",
 "version": "v0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
