
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-02T17:33:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7e69b040a56a239fb10100a4fff950e6f3b6903",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
