[tool.poetry]
name = "vfaf"
version = "0.1.0"
description = ""
authors = ["Javier Daza <javierjdaza@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.3"
matplotlib = "^3.5.2"
seaborn = "^0.11.2"
numpy = "^1.23.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
