[project]
name = "examplePackageYassun"
version = "1.2.1"
authors = [
  { name="Yassun BlueLightning", email="yassunapp@gmail.com" },
]
description = "A small example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://www.facebook.com/yassunapp"
"Bug Tracker" = "https://www.facebook.com/yassunapp"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
