[tool.poetry]
name = "yahoo-finance-cache"
version = "0.1.3"
description = ""
authors = ["IsaacBreen <57783927+IsaacBreen@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.3"
pandas-datareader = "^0.10.0"
dateparser = "^1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
