[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "osuca"
version = "2.2.2"
dependencies = [
    "Flask",
    "flask-restful",
    "requests",
    "flask-cors"
]
authors = [
  { name="Tolga Ozbakan", email="tolga@ozbakan.com" },
]
description = "OSU Course Analytics"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ozbakan/osuca"