[tool.poetry]
name = "hangarmc-hangar"
version = "0.1.0"
description = ""
authors = ["Oskar <56176746+OskarZyg@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
urllib3 = "^1.26.10"
python-dateutil = "^2.8.2"
orjson = "^3.7.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
