# coding: utf-8

"""
    external/v1/external_session_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""


import pprint
import re  # noqa: F401
from typing import TYPE_CHECKING

import six

from grid.openapi.configuration import Configuration

if TYPE_CHECKING:
    from datetime import datetime
    from grid.openapi.models import *

class V1ListFilesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_list': 'list[V1File]',
        'parent_dir': 'str'
    }

    attribute_map = {
        'file_list': 'fileList',
        'parent_dir': 'parentDir'
    }

    def __init__(self, file_list: 'list[V1File]' = None, parent_dir: 'str' = None, _configuration=None):  # noqa: E501
        """V1ListFilesResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._file_list = None
        self._parent_dir = None
        self.discriminator = None

        if file_list is not None:
            self.file_list = file_list
        if parent_dir is not None:
            self.parent_dir = parent_dir

    @property
    def file_list(self) -> 'list[V1File]':
        """Gets the file_list of this V1ListFilesResponse.  # noqa: E501


        :return: The file_list of this V1ListFilesResponse.  # noqa: E501
        :rtype: list[V1File]
        """
        return self._file_list

    @file_list.setter
    def file_list(self, file_list: 'list[V1File]'):
        """Sets the file_list of this V1ListFilesResponse.


        :param file_list: The file_list of this V1ListFilesResponse.  # noqa: E501
        :type: list[V1File]
        """

        self._file_list = file_list

    @property
    def parent_dir(self) -> 'str':
        """Gets the parent_dir of this V1ListFilesResponse.  # noqa: E501


        :return: The parent_dir of this V1ListFilesResponse.  # noqa: E501
        :rtype: str
        """
        return self._parent_dir

    @parent_dir.setter
    def parent_dir(self, parent_dir: 'str'):
        """Sets the parent_dir of this V1ListFilesResponse.


        :param parent_dir: The parent_dir of this V1ListFilesResponse.  # noqa: E501
        :type: str
        """

        self._parent_dir = parent_dir

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ListFilesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ListFilesResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ListFilesResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: 'V1ListFilesResponse') -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1ListFilesResponse):
            return True

        return self.to_dict() != other.to_dict()
