[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
norecursedirs = ".git"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '/\..+/'

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true
