[tool.poetry]
name = "craterpy"
version = "0.5.2"
homepage = "https://github.com/cjtu/craterpy"
description = "Impact crater data science in Python."
authors = ["Christian J. Tai Udovicic <cj.taiudovicic@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cjtu/craterpy"
documentation = "https://readthedocs.org/projects/craterpy/"
classifiers=[
'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: Astronomy',
    'Programming Language :: Python :: 3.8',
]
keywords = [
    'python', 
    'crater',
    'data analysis',
    'planetary',
    'moon',
]
include = [
    "LICENSE.txt",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/cjtu/craterpy/issues"

[tool.poetry.dependencies]
python = "^3.8,<3.10"
numpy = "^1.20.2"
matplotlib = "^3.4.2"
pandas = "^1.2.4"
rasterio = "^1.2.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
jupyter = "^1.0.0"
pylint = "^2.8.2"
black = "^22.6"
pytest-cov = "^2.11.1"
myst-parser = "^0.18.0"
sphinx = "^5.1.1"
sphinx-rtd-theme = "^1.0.0"

[tool.black]
line-length=79

[tool.pylint.reports]
output-format="colorized"
reports="y"
disable=["R0913","C0103","W0212","R0914","E1121","W0511","C0209"]
msg-template="{msg_id}:{line:3d},{column}: {obj}: {msg}"

[tool.pytest.ini_options]
addopts = "--cov=craterpy --cov-branch --cov-report term-missing  -vv --color=yes"
python_files = "tests.py test_*.py *_tests.py"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
