[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "greymatter"
description = "Grey Matter reduces the time it takes to get up and running with Selenium."
version = "0.1alpha1"
license = { text = "GNU General Public License (GPL)" }
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: Microsoft :: Windows",
]
dependencies = [
    "requests",
    "selenium"
]
requires-python = ">=3.7"