
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-01T15:11:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6811bac3bf8c5332ecabd2d24c1ac7b129a08b1c",
 "version": "0.2.17.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
