
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T10:46:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a1acdf5c7e8b41585237b6d5503384100a039be",
 "version": "0.3.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
