[tool.poetry]
name = "dlt-metabase-source"
version = "0.0.25"
description = ""
authors = [
    "Adrian Brudaru <adrian@scalevector.ai>"
]
license = "apache"
readme = "README.md"
packages = [
    { include = "dlt_metabase_source" }
]

[tool.poetry.dependencies]
python ="^3.8"
python-dlt  = "^=0.1.0rc6"
google-cloud-bigquery = "^=2.34.4"
psycopg2-binary = "^=2.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
