[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "casper7-plugin-wordle-reactions"
version = "0.4.2"
description = "a casper7 plugin that reacts to wordle results"
authors = ["backwardspy <backwardspy@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "casper7_plugin_wordle_reactions"}]
repository = "https://github.com/backwardspy/casper7-plugin-wordle-reactions"

[tool.poetry.scripts]
casper7-plugin-wordle-reactions = "casper7_plugin_wordle_reactions.run:plugin"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.dependencies]
python = "^3.10"
docopt-ng = "^0.8.1"
pydantic = "^1.9.1"

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
pylint = "^2.14.1"
mypy = "^0.961"
ward = "^0.66.0b0"
ptpython = "^3.0.20"
isort = "^5.10.1"
