[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NiuLab-crawl-YouTube-screenshots"
version = "2.0.0"
authors = [
  { name="Shuo Niu, Abhisan Ghimire", email="invictuscreatesanapp@gmail.com" },
]
description = "Downloads Youtube Clips on given interval of time"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]