
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-31T18:09:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "29d94979184f5842155b2250ad87cbef0f9df138",
 "version": "2.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
