[tool.poetry]
name = "python-event-sourcery"
version = "0.0.2"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
packages = [
    { include = "event_sourcery" },
    { include = "event_sourcery_pydantic" },
    { include = "event_sourcery_sqlalchemy" },
]

[tool.poetry.dependencies]
python = "3.10"
pydantic = "^1.9"
SQLAlchemy = "^1.4"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
bandit = "^1.7.4"
mypy = "^0.971"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
