# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/./couchbase_version.py
# at
#    2022-08-02 12:40:56.218464
__version__ = '4.0.3rc1'