[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyntegrals"
version = "1.0.0"
description = "A tool for calculating definite integrals over a 2D polygonal domain"
readme = "README.md"
authors = [{ name = "quacksort", email = "quacksort@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["integral", "polygon", "double integral"]
dependencies = [
    "numpy",
    "tripy",
    "scipy",
    "shapely",
]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["pyntegrals"]

[project.urls]
Homepage = "https://github.com/quacksort/pyntegrals"

#[project.scripts]
#realpython = "examples/example.__main__:main"