[build-system]
requires = ['setuptools>=61.0.0', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'kurek'
version = '0.2.1'
description = 'Download photos and videos from zbiornik.com'
readme = 'README.md'
authors = [{ name = 'Bartosz Bartyzel', email = 'barnxba@gmail.com'}]
license = { file = 'LICENSE.md' }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["kurek", "zbiornik", "zbiornik.com"]
dependencies = [
    "aiofiles >= 0.8.0",
    "aiohttp >= 3.8.1",
    "beautifulsoup4 >= 4.11.1",
    "yarl >= 1.7.2",
    "tqdm >= 4.64.0",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/barnxba/kurek"

[project.scripts]
kurek = "kurek.__main__:entry"
