
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-31T19:40:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "381b8ec34da07e919098688dadfeb5d8f578d56e",
 "version": "2022.7.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
