[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auth0rization"
version = "1.0.0"
authors = [
  { name="Nicholas Biegel", email="contact@nbiegel.com" },
]
description = "A package to perform actions related to auth0 JWT tokens."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
      "Intended Audience :: Developers",
      "Natural Language :: English",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3.6",
      "Programming Language :: Python :: 3.7",
      "Programming Language :: Python :: 3.8",
      "Programming Language :: Python :: 3.9",
      "Programming Language :: Python :: 3.10",
      "Topic :: Security",
      "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
   "jwcrypto >= 1.0",
   "requests >= 2.27.1",
]

[project.optional-dependencies]
dev = [
   "coverage",
   "pylint",
   "build",
   "twine",
]

[project.urls]
"Homepage" = "https://github.com/nbiegel/auth0rization-python"
"Bug Tracker" = "https://github.com/nbiegel/auth0rization-python/issues"
