[build-system]
requires = ["setuptools>=59.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "editdist"
version = "0.0.1"
authors = [
  { name="Lillian Zhu", email="zhuy0713@gmail.com" },
]
description = "Package for getting edit distance"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yining0713/edit-distance"
"Bug Tracker" = "https://github.com/yining0713/edit-distance/issues"
