[project]
name = "monobit"
version = "0.0.1"
authors = [
    { name = "Rob Hagemans", email = "rob.hagemans@hotmail.com" },
]
description = "Tools for working with monochrome bitmap fonts."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
]
keywords = [
    "font", "retro", "bitfont", "bitmap-font", "8-bit"
]

[project.urls]
"Homepage" = "http://pc-basic.org"

