[tool.poetry]
name = "soroban-sdk"
version = "0.0.1.dev0"
description = ""
authors = ["Jun Luo <4catcode@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
