[tool.poetry]
name = "moss_emspy"
version = "1.2.5"
description = "Package to interact with MOSS WEGA-EMS"
license = "MIT"
authors = ["M.O.S.S.Computer Grafik Systeme GmbH <develop@moss.de>"]
maintainers = ["M.O.S.S.Computer Grafik Systeme GmbH <develop@moss.de>"]
homepage = "https://www.moss.de/"
packages = [{ include = "moss" }]
readme = "README.md"
include = ["CHANGELOG.md"]
keywords = ["wegaems",]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Environment :: Other Environment",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = ">=2.7,<3.0 || >=3.7,<4"
requests = "^2.18.0"
typing = {version = "^3.7.4", python = "< 3.5"}
anytree = "^2.8.0"
tqdm = "^4.58.0"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", python = ">=3.6"}
pytest = {version = "^4"}
tox = "^3.14.1"
isort = "^4.3.21"
flake8 = "^3.7.9"
dlint = "^0.10.3"
auto-changelog = {version = "^0.5.1", python = ">=3.5"}
pytest-mock = "2.0.0"
mock = "3.0.5"
pytest-cov = "^2.11.1"
pyinstaller = {version = "^4.2.0", python = ">=3.5"}
docutils= {version = "0.12"}
taskipy = {version = "^1.9.0", python =">=3.5"}
mkdocs = {version = "^1.2.3", python = ">=3.7,<4"}
mkdocs-material = {version = "^7.3.6", python = ">=3.7,<4"}
importlib-metadata = {version = "^4.8.2", python = ">=3.7,<4"}
mkdocstrings = {version = "^0.16.2", python = ">=3.7,<4"}
mkdocs-autorefs = {version = "0.3.0", python = ">=3.7,<4"}
pre-commit = {version = "^2.17.0", python = ">=3.7,<4"}

[tool.poetry.scripts]
ems_cli = "moss.ems.scripts.ems_cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"

[tool.taskipy.tasks]
docs = "task generate_apidoc && task generate_docs"
generate_apidoc = "poetry run sphinx-apidoc -o ./docs/source/ ./moss/ ./moss/ems/extra/ ./moss/ems/scripts/ ./moss/ems/scripts/utilities/"
generate_docs = "poetry run docs\\make.bat html ./docs/source/ ./docs/build"

docs_jenkins = "task generate_apidoc_jenkins && task generate_docs_jenkins"
generate_docs_jenkins = "cd docs && make html"
generate_apidoc_jenkins = "poetry run sphinx-apidoc -o ./docs/source/ ./moss/ ./moss/ems/extra/ ./moss/ems/scripts/ ./moss/ems/scripts/utilities/"

[tool.black]
target-version = ['py37']
experimental_string_processing = true
force-exclude = '''
.*/setup\.py$
'''