
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T15:01:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "22ae70ceb75620dbb8427ab6d0b58250e21c3d25",
 "version": "1.17.0.post.dev87"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
