[tool.poetry]
name = "pytest_assurka"
version = "0.2.5"
description = "A pytest plugin for Assurka Studio"
authors = ["Assurka Limited"]
readme = "README.md"
keywords = ["testing", "development", "pytest", "assurka", "assurka_io"]
classifiers = [
  "Framework :: Pytest",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
packages = [
    { include = "pytest_assurka"}
]

[tool.poetry.plugins.pytest11]
assurka = "pytest_assurka.plugin"


[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[tool.poetry.urls]
Homepage = "https://www.assurka.io"
Studio = "https://studio.assurka.io"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
