[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "servd"
version = "1.0.0"
description = "Python daemonizer for Unix, Linux and OS X."
authors = ["Server Density"]
maintainers = ["LW016"]
readme = "README.rst"
repository = "https://github.com/lw016/servd"
keywords = ["daemon", "service", "unix"]
license="http://creativecommons.org/licenses/by-sa/3.0/"
classifiers=[
    "License :: OSI Approved :: Attribution Assurance License",
    "Intended Audience :: Developers",
    "Environment :: No Input/Output (Daemon)",
    "Operating System :: Unix",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries"
    ]
