[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloud_cache"
version = "0.0.1"
authors = [
    { name="voyager18", email="research@vulcancyber.io" },
]
description = "emty public cloud_cache"
requires-python = ">=3.7"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]

[tool.setuptools.packages]
find = {}