
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-30T17:32:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "47de3556568f5537fa6199361a9fcedb91860347",
 "version": "2022.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
