# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# configuration of a single parameter of an axis transformation
class KinCfgAxsTrafoSingleParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKinCfgAxsTrafoSingleParam(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KinCfgAxsTrafoSingleParam()
        x.Init(buf, n + offset)
        return x

    # KinCfgAxsTrafoSingleParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # name of the parameter
    # KinCfgAxsTrafoSingleParam
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # value of the parameter (when it's a double value)
    # KinCfgAxsTrafoSingleParam
    def ValueDouble(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # value of the parameter (when it's a integer value)
    # KinCfgAxsTrafoSingleParam
    def ValueInt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # value of the parameter (when it's a string value)
    # KinCfgAxsTrafoSingleParam
    def ValueString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def KinCfgAxsTrafoSingleParamStart(builder): builder.StartObject(4)
def KinCfgAxsTrafoSingleParamAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def KinCfgAxsTrafoSingleParamAddValueDouble(builder, valueDouble): builder.PrependFloat64Slot(1, valueDouble, 0.0)
def KinCfgAxsTrafoSingleParamAddValueInt(builder, valueInt): builder.PrependInt64Slot(2, valueInt, 0)
def KinCfgAxsTrafoSingleParamAddValueString(builder, valueString): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(valueString), 0)
def KinCfgAxsTrafoSingleParamEnd(builder): return builder.EndObject()


class KinCfgAxsTrafoSingleParamT(object):

    # KinCfgAxsTrafoSingleParamT
    def __init__(self):
        self.name = None  # type: str
        self.valueDouble = 0.0  # type: float
        self.valueInt = 0  # type: int
        self.valueString = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        kinCfgAxsTrafoSingleParam = KinCfgAxsTrafoSingleParam()
        kinCfgAxsTrafoSingleParam.Init(buf, pos)
        return cls.InitFromObj(kinCfgAxsTrafoSingleParam)

    @classmethod
    def InitFromObj(cls, kinCfgAxsTrafoSingleParam):
        x = KinCfgAxsTrafoSingleParamT()
        x._UnPack(kinCfgAxsTrafoSingleParam)
        return x

    # KinCfgAxsTrafoSingleParamT
    def _UnPack(self, kinCfgAxsTrafoSingleParam):
        if kinCfgAxsTrafoSingleParam is None:
            return
        self.name = kinCfgAxsTrafoSingleParam.Name()
        self.valueDouble = kinCfgAxsTrafoSingleParam.ValueDouble()
        self.valueInt = kinCfgAxsTrafoSingleParam.ValueInt()
        self.valueString = kinCfgAxsTrafoSingleParam.ValueString()

    # KinCfgAxsTrafoSingleParamT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.valueString is not None:
            valueString = builder.CreateString(self.valueString)
        KinCfgAxsTrafoSingleParamStart(builder)
        if self.name is not None:
            KinCfgAxsTrafoSingleParamAddName(builder, name)
        KinCfgAxsTrafoSingleParamAddValueDouble(builder, self.valueDouble)
        KinCfgAxsTrafoSingleParamAddValueInt(builder, self.valueInt)
        if self.valueString is not None:
            KinCfgAxsTrafoSingleParamAddValueString(builder, valueString)
        kinCfgAxsTrafoSingleParam = KinCfgAxsTrafoSingleParamEnd(builder)
        return kinCfgAxsTrafoSingleParam
