
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T09:14:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d0c939da77b3164c445aab2d473843ae5f0c330",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
