[tool.poetry]
name = "readtime_cli"
version = "0.2.2"
description = "CLI to calculates the time some text takes the average human to read, based on Medium's read time forumula."
authors = ["Felipe Guedes <contatofelipeguedes@gmail.com>"]
readme = "README.md"
repository = "https://github.com/guedesfelipe/readtime_cli"
documentation = "https://github.com/guedesfelipe/readtime_cli"
keywords = ["python", "readtime", "readtime_cli", "cli"]

[tool.poetry.scripts]
readtime = "readtime_cli.main:app"

[tool.poetry.dependencies]
python = "^3.8"
readtime = "^2.0.0"
lxml = "4.9.0"
typer = {extras = ["all"], version = "^0.6.1"}

[tool.poetry.dev-dependencies]
pytest = "^7.1"
blue = "^0.9.0"
isort = "^5.10.1"
prospector = { extras = ["with_mypy"], version = "^1.7.7" }
pytest-cov = "^3.0.0"
ipdb = "^0.13.9"
safety = "^2.1.1"
types-setuptools = "^63.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
