# this will reproduce the version from tags to match versioningit
{% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
{% set version_number = '_' + version_number if version_number != '0' else '' %}

{% set version = version_tag + version_number %}

package:
  name: "maverick"
  version:

source:
  path: ..

build:
  noarch: python
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python

  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - maverick

about:
  home: https://github.com/ornlneutronimaging/maverick
  license: GPL (version 3)
  license_family: GPL3
  license_file: ../LICENSE
  summary: TOF Imaging Grating Interferometry Pre-Processing Tool

extra:
  recipe-maintainers:
    - JeanBilheux
