[tool.poetry]
name = "qwixtractor"
version = "0.1.0"
description = "Extract data from the Quarterly Workforce Indicators"
authors = ["Rodrigo Franco"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
pandas = ">=1.4.3"
requests = ">=2.28.1"
progressbar2 = ">=4.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
myst-nb = {version = "^0.16.0", python = "^3.9"}
sphinx-autoapi = "^1.9.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
