[tool.poetry]
name = "fcengine"
version = "1.0"
description = "Python module for making console games"
authors = ["Fab4key"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
