[tool.pyright]
include = ["disnake_ext_components"]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportPrivateUsage = false
reportImportCycles = false

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.mypy]
namespace_packages = true
files = ["disnake_ext_components/*.py"]

[tool.pytest.ini_options]
required_plugins = ["pytest-asyncio"]
asyncio_mode = "strict"
testpaths = ["tests"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@t.overload"]