---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sushy
  name: sushy
  namespace: openshift-infra
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sushy
