[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "earthworm"
version = "0.0.1"
authors = [
  { name="frozencookie", email="cookie.monster.yan@hotmail.com" },
]
description = "Some utils for preocessing timeseries data."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitee.com/frozencookie/earthworm"
"Bug Tracker" = "https://gitee.com/frozencookie/earthworm/issues"