[tool.poetry]
name = "flask-lan"
version = "0.1.3"
description = "Flask-Lan is a schema validator and swagger generator but more modernized"
authors = ["chaojie <zhuzhezhe95@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "flask_lan"}]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.1.3"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.1.2"
black = "^22.6.0"
isort = "^5.10.1"
coverage = "^6.4.2"
mkdocs = "^1.3.1"
mkdocs-material = "^8.3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"