version: 2

python:
  version: 3.7
  install:
    - requirements: doc/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
  system_packages: true

