[tool.poetry]
name = "mf_manifest_tools_simple"
version = "0.7.10"
description = "MF Manifest Tools Simple"
authors = ["xx"]

[tool.poetry.scripts]
mf_manifest_tools_simple = 'mf_manifest_tools_simple:main'

[tool.poetry.dependencies]
python = ">=3.6"
docopt = ">=0.6.2"
lxml = ">=4.6.3"
graphviz = ">=0.16"
loguru = ">=0.5.3"
inflection = ">=0.5.1"
dataclasses = { version = "^0.8", python = "<3.7" }
pyyaml = ">=5.4.1"
openpyxl = ">=3.0.7"
PyPDF2 = ">=1.26.0"
jsonschema = ">=3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple"
default = true
