/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   constr_if.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CONSTR_IF_H
#define UHDM_CONSTR_IF_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/SymbolFactory.h>
#include <uhdm/containers.h>
#include <uhdm/constraint_expr.h>




namespace UHDM {
class expr;


class constr_if final : public constraint_expr {
  UHDM_IMPLEMENT_RTTI(constr_if, constraint_expr)
public:
  // Implicit constructor used to initialize all members,
  // comment: constr_if();
  virtual ~constr_if() final = default;


  virtual const BaseClass* VpiParent() const final { return vpiParent_; }

  virtual bool VpiParent(BaseClass* data) final { vpiParent_ = data; if (data) uhdmParentType_ = data->UhdmType(); return true;}

  virtual unsigned int UhdmParentType() const final { return uhdmParentType_; }

  virtual bool UhdmParentType(unsigned int data) final { uhdmParentType_ = data; return true;}

  virtual bool VpiFile(const std::string& data) final;

  virtual const std::string& VpiFile() const final;

  virtual unsigned int UhdmId() const final { return uhdmId_; }

  virtual bool UhdmId(unsigned int data) final { uhdmId_ = data; return true;}

  virtual constr_if* DeepClone(Serializer* serializer, ElaboratorListener* elab_listener, BaseClass* parent) const override;

  VectorOfconstraint_expr* Constraint_exprs() const { return constraint_exprs_; }

  bool Constraint_exprs(VectorOfconstraint_expr* data) { constraint_exprs_ = data; return true;}

  const expr* Condition() const { return condition_; }

  bool Condition(expr* data) { condition_ = data; return true;}

  virtual unsigned int VpiType() const final { return vpiConstrIf; }


  virtual  UHDM_OBJECT_TYPE UhdmType() const final { return uhdmconstr_if; }

protected:
  void DeepCopy(constr_if* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:

  BaseClass* vpiParent_ = nullptr;

  unsigned int uhdmParentType_ = 0;

  SymbolFactory::ID vpiFile_ = 0;

  unsigned int uhdmId_ = 0;

  VectorOfconstraint_expr* constraint_exprs_ = nullptr;

  expr* condition_ = nullptr;

};


typedef FactoryT<constr_if> constr_ifFactory;


typedef FactoryT<std::vector<constr_if *>> VectorOfconstr_ifFactory;

}  // namespace UHDM

#endif
