
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T12:41:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0437d61247ad831fe399375b787a93d755ad508e",
 "version": "0.2.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
