[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
[project]
name = 'amidala'
version = '0.0.1'
authors = [{name="João Rocha"}]
description = 'This is a placeholder for the package amidala. This package analyzes data collected from evaluating strategies that mitigate the phase ordering problem.'
readme = 'README.md'
requires-python = '>=3.7'
[project.scripts]
amidala = 'amidala.app:run'
