[tool.poetry]
name = "parse-IEX"
version = "0.1.1"
description = "Parse IEX market data streams"
license = "BSD-2-Clause"
authors = ["Amit Goren"]
readme = "README.md"
homepage = "https://github.com/mmatamm/parse-IEX"
repository = "https://github.com/mmatamm/parse-IEX.git"
keywords = ["IEX"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
