[tool.poetry]
name = "otlet"
version = "1.0.0"
description = "Zero-dependency, pure-python wrapper for the PyPI JSON Web API"
readme = "README.md"
documentation = "https://otlet.readthedocs.io/en/latest/"
repository = "https://github.com/nhtnr/otlet"
license = "MIT"
authors = ["Noah Tanner (nhtnr) <noahtnr@gmail.com>"]
classifiers = ["Development Status :: 5 - Production/Stable",  "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "License :: OSI Approved :: BSD License", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 3 :: Only"]

[tool.poetry.dependencies]
python = "^3.6.2"
Sphinx = {version = "^4.5.0", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}
otlet-cli = {version = "^1.0.0", optional = true, python = "^3.7"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mypy = "^0.931"
black = "^22.6.0"
radon = "^5.1.0"
pylint = [
    {version = "~2.13", python = "~3.6.2"},
    {version = "^2.14.4", python = "^3.7.2"}
]

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme"]
cli = ["otlet-cli"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
