[tool.poetry]
name = "chiral-db-grpc-client"
version = "0.0.4"
description = "ChiralDB gRPC Client in Python"
authors = ["Qin Wan <rogerwq@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"