[tool.poetry]
name = "path-tree-generator"
version = "0.3.1"
description = "Generate tree-like directory listings for humans and output them as str, list[str], dict or json."
authors = ["DL6NM <mail@dl6nm.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dl6nm/path-tree-generator"
keywords = ["path", "tree", "generator", "json", "converter", "directory", "dir", "human-readable", "tree-like", "linux"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Other Audience",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Topic :: Software Development",
    "Topic :: System :: Filesystems",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-datadir = "^1.3.1"

[tool.pytest.ini_options]
addopts = [
    "--cov=path_tree_generator",
    "--tb=short",
    "--cov-report=html",
#    "--showlocals",
#    "--setup-show",
#    "--disable-warnings",
]
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

