[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyeditdistance"
version = "1.0.1"
authors = [
  { name="Carlton Shepherd", email="carlton@linux.com" },
]
description = "A pure, minimalist, no-dependency Python library of various edit distances."
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Text Processing",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

[project.urls]
"Homepage" = "https://github.com/cgshep/pyeditdistance"
"Bug Tracker" = "https://github.com/cgshep/pyeditdistance/issues"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
