[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "spotify_playlists_mover"
version = "1.0.0"
authors = [
	{ name="Alberto Pasqualetto", email="39854348+albertopasqualetto@users.noreply.github.com" },
]
description = "Move all your Spotify playlists and saved songs to a new account"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
dependencies = [
	"spotipy>=2.20.0"
]
keywords = ["Spotify"]
classifiers = [
	"Programming Language :: Python :: 3",
	"Environment :: Console",
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: OS Independent",
	"Topic :: Utilities"
]

[project.urls]
"Homepage" = "https://github.com/albertopasqualetto/spotify-playlists-mover"
"Bug Tracker" = "https://github.com/albertopasqualetto/spotify-playlists-mover/issues"

[project.scripts]
spotify_playlists_mover = "spotify_playlists_mover.__main__:main"