[tool.poetry]
name = "cognite-wells-sdk"
version = "0.14.9"
description = ""
authors = ["Sigurd Holsen <sigurd.holsen@cognite.com>"]
packages = [
    { include="cognite" },
]
readme = "cognite/well_model/README.md"

[tool.poetry.dependencies]
python = "^3.7.0"
cognite-logger = "^0.5.0"
requests = "^2.21.0"
numpy = "^1.18.1"
pandas = "^1.0.1"
nulltype = "^2.3.1"
requests-oauthlib = "^1.3.0"
oauthlib = "^3.1.0"
pydantic = "^1.8"
msal = "^1.13.0"
matplotlib = "^3.4.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.5.2"
flake8 = "^3.8.4"
mypy = "^0.790"
pre-commit = "^2.7.1"
pytest = "^6.0.1"
jupyter = "^1.0.0"
plotly = "^4.10.0"
matplotlib = "^3.1.3"
testfixtures = "^6.14.2"
datamodel-code-generator = "^0.11.12"
cognite-sdk = "2.12.2"
jupyterlab = "^3.1.7"
psycopg2-binary = "^2.9.1"
jblack = "^1.2"
Sphinx = "^3.0.0"
sphinx-rtd-theme = "^1.0.0"
autodoc-pydantic = "^1.5.0"
coloredlogs = "^15.0.1"
nbsphinx = "^0.8.8"

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # isort all Python files
known_third_party = []


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
