[build-system]
requires = ["setuptools >= 52", "setuptools_scm >= 6.2", "Cython >= 0.29.20"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dnaio/_version.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
