[tool.poetry]
name = "fin-data"
version = "0.5.3"
description = ""
authors = ["Dan Kelleher <kelleherjdan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "^1.4.28"
ready-logger = "^0.1.0"
cytoolz = "^0.11.2"
asyncpg = "^0.25.0"
psycopg = {version= "^3.0.15",  extras=["c"]}

# export.
s3fs = { version = "^2022.5.0", optional = true }
boto3 = { version = "1.21.0", optional = true }
pandas = { version = "^1.4.2", optional = true }
pyarrow = { version = "^8.0.0", optional = true }
sh = "^1.14.2"
pydantic = "^1.9.1"


[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.16.0"
black = "^21.12b0"
#fin_data_testing = {path = "../fin-data-testing", develop=true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
export = ["s3fs", "boto3", "pandas", "pyarrow"]

