
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-31T13:10:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3e4ba6ac79301d21fff25294edc425dfbe0426f",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
