[tool.poetry]
name = "voicemeeter-compact"
version = "1.3.1"
description = "A Compact Voicemeeter Remote App"
authors = ["onyx-and-iris <code@onyxandiris.online>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/onyx-and-iris/voicemeeter-compact"

packages = [
    { include = "vmcompact" },
]
include = ["vmcompact/img/cat.ico"]

[tool.poetry.dependencies]
python = "^3.11"
sv-ttk = "^0.1"
voicemeeter-api = { version = "^0.6.0", python = "^3.10" }
vban-cmd = { version = "^1.3.0", python = "^3.10" }

[tool.poetry.dev-dependencies]
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
