/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   func_call.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_FUNC_CALL_H
#define UHDM_FUNC_CALL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/SymbolFactory.h>
#include <uhdm/containers.h>
#include <uhdm/tf_call.h>




namespace UHDM {
class function;


class func_call final : public tf_call {
  UHDM_IMPLEMENT_RTTI(func_call, tf_call)
public:
  // Implicit constructor used to initialize all members,
  // comment: func_call();
  virtual ~func_call() final = default;


  virtual const BaseClass* VpiParent() const final { return vpiParent_; }

  virtual bool VpiParent(BaseClass* data) final { vpiParent_ = data; if (data) uhdmParentType_ = data->UhdmType(); return true;}

  virtual unsigned int UhdmParentType() const final { return uhdmParentType_; }

  virtual bool UhdmParentType(unsigned int data) final { uhdmParentType_ = data; return true;}

  virtual bool VpiFile(const std::string& data) final;

  virtual const std::string& VpiFile() const final;

  virtual unsigned int UhdmId() const final { return uhdmId_; }

  virtual bool UhdmId(unsigned int data) final { uhdmId_ = data; return true;}

  virtual tf_call* DeepClone(Serializer* serializer, ElaboratorListener* elab_listener, BaseClass* parent) const override;

  int VpiFuncType() const { return vpiFuncType_; }

  bool VpiFuncType(int data) { vpiFuncType_ = data; return true;}

  const function* Function() const { return function_; }

  bool Function(function* data) { function_ = data; return true;}

  virtual unsigned int VpiType() const final { return vpiFuncCall; }


  virtual  UHDM_OBJECT_TYPE UhdmType() const final { return uhdmfunc_call; }

protected:
  void DeepCopy(func_call* clone, Serializer* serializer,
                ElaboratorListener* elaborator, BaseClass* parent) const;

private:

  BaseClass* vpiParent_ = nullptr;

  unsigned int uhdmParentType_ = 0;

  SymbolFactory::ID vpiFile_ = 0;

  unsigned int uhdmId_ = 0;

  int vpiFuncType_ = 0;

  function* function_ = nullptr;

};


typedef FactoryT<func_call> func_callFactory;


typedef FactoryT<std::vector<func_call *>> VectorOffunc_callFactory;

}  // namespace UHDM

#endif
