name: pydaymet-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp>=3.8.1
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotli
  - cchardet
  - cytoolz
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib<0.26
  - pydantic
  - pyyaml
  - pyproj>=1.2
  - requests
  - requests-cache>=0.8
  - shapely
  - urllib3

  # pygeoutils deps
  - dask-core
  - geopandas>=0.8
  - netcdf4
  - numpy>=1.17
  - pygeos
  - rasterio>=1.2
  - scipy
  - xarray>=0.18
  - rioxarray>=0.10

  # py3dep
  - click>=7.0
  - richdem>=0.3.4

  # optional deps to speed up xarray and pydaymet
  - bottleneck
  - numba

  # test deps
  - pyarrow>=1.0.1
  - psutil
  - pytest-cov
  - pytest-xdist

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/py3dep.git
