[tool.poetry]
name = "scraper-api"
version = "0.1.0"
description = "CI/CD pipelines for scraper library"
authors = ["Daniil Trotsenko <daniil.trotsenko.dev@gmail.com>"]
maintainers = ["Daniil Trotsenko <daniil.trotsenko.dev@gmail.com>"]


classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]


packages = [
    { include = "scraper" },
]
readme = "README.md"


repository = "https://github.com/danik-tro/scraper-ci-cd-library"
homepage = "https://github.com/danik-tro/scraper-ci-cd-library"
documentation = "https://danik-tro.github.io/scraper-ci-cd-library/"


[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.971"
pre-commit = "^2.20.0"
mkdocs = "^1.3.1"
mkdocstrings = {version = ">=0.18", extras = ["python"]}
mkdocs-material = "^8.3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Linters

## Black configuration
[tool.black]
line-length = 89
extend-exclude = '''
(
    migrations
)
'''
target-version = ['py310']

## Isort configuration
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 89
### Black-compatible isort configuration
force_grid_wrap = 0
use_parentheses = true
old_finders = true


[tool.pytest.ini_options]
testpaths = "tests"
addopts = "-p no:warnings -vv"
