[workspace]

members = [
  "glean-core",
  "glean-core/rlb",
  "glean-core/bundle",
  "glean-core/bundle-android",
  "tools/embedded-uniffi-bindgen",
]

default-members = [
  "glean-core",
  "glean-core/rlb",
  "tools/embedded-uniffi-bindgen",
]

exclude = [
  "samples/multi-bindings"
]

[profile.release]
opt-level = "s"
debug = false
lto = true
