[project]
name = "wumpy-rest"
version = "0.3.0"
description = "Reusable and richly typed wrapper over the Discord REST API"
readme = {file = "README.md", content-type="text/markdown"}

# Both httpx and anyio has 3.6.2 as the minimum requirement
# but @contextlib.asynccontextmanager was added in Python 3.7
requires-python = ">=3.7"

license = {text = "Dual-licensed under the Apache License 2.0 and the MIT License"}
authors = [{name = "Bluenix", email = "bluenixdev@gmail.com"}]

keywords = [
    "wumpy", "wumpus", "wrapper",
    "discord", "discord-api", "discord-bot", "discord-api-wrapper",
    "python-3"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AnyIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

dependencies = [
    "anyio >= 3.3.4, <4",
    "httpx[http2] >= 0.22, < 1",
    "discord-typings >= 0.5.0, < 1"
]

[project.urls]
Homepage = "https://github.com/wumpyproject/wumpy"
Repository = "https://github.com/wumpyproject/wumpy/tree/main/library/wumpy-rest"
Documentation = "https://wumpy.rtfd.io"

[build-system]
requires = ["flit_core >=3.5, <4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
# This is a subpackage under the wumpy namespace package,
# we need to tell flit this otherwise it tries to make the
# import wumpy-rest rather than wumpy.rest
name = "wumpy.rest"
