# 后端接口地址配置

search:
  dataset: http://192.168.55.37:30000/devkitClient/dataSetList
  resource: http://192.168.55.37:30000/devkitClient/findRes
  docker: http://192.168.55.37:30000/devkitClient/getDockerImagesInfo

download:
  dataset: http://192.168.55.37:30000/devkitClient/downDataSet
  resource: http://192.168.55.37:30000/devkitClient/downRes

list:
  resource: http://192.168.55.37:30000/devkitClient/resList

info:
  dataset: http://192.168.55.37:30000/
  resource: http://192.168.55.37:30000/devkitClient/getInfo