[tool.poetry]
name = "hangarmc-hangar"
version = "1.0.0"
description = "Hangar SDK for python"
readme = "README.md"
license = "MIT"
authors = ["Oskar <56176746+OskarZyg@users.noreply.github.com>"]

homepage = "https://pypi.org/project/hangarmc-hangar/"
repository = "https://github.com/OskarsMC-Network/hangarmc-hangar/"
documentation = "https://github.com/OskarsMC-Network/hangarmc-hangar/blob/main/README.md"

[tool.poetry.dependencies]
python = "^3.10"
urllib3 = "^1.26.11"
python-dateutil = "^2.8.2"
orjson = "^3.7.8"

[tool.poetry.dev-dependencies]
#pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
