_target_: pytorch_lightning.Trainer

gpus: 1
precision: 16

min_epochs: 2
max_epochs: 20

profiler: "simple"
progress_bar_refresh_rate: 5
weights_summary: "full"


# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
# SWA
stochastic_weight_avg: False
# 梯度积累
accumulate_grad_batches: 1

# ckpt path
resume_from_checkpoint: null
