[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nia-toolbox"
version = "0.0.1"
authors = [
  { name="Ma Feilong", email="mafeilong@gmail.com" },
]
description = "NeuroImaging Analysis ToolBox. This package is an alias for nia-tb."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "nia-tb",
]

[project.urls]
"Homepage" = "https://github.com/feilong/nia-tb"
"Bug Tracker" = "https://github.com/feilong/nia-tb/issues"

[tool.setuptools.packages.find]
where = ["src"]
