DEFAULTS = {
        "_DEFAULT_MEMORY_MODE" : 'low',
        "_DEFAULT_DISK_MODE" : 'low',
        "_DEFAULT_OUTPUT_MODE" : 'notebook',
        "_NO_BATCH" : None,
        "_DEFAULT_RELOAD" : None,
        "_DEFAULT_VARIANT" : None,
        "_DEFAULT_FLOW" : None,
        "_DEFAULT_ENGINE" : 'pandas',
        "_DEFAULT_DATATYPE" : 'dataframe',
        "_DEFAULT_CHUNK_SIZE" : 500000,
        "_DEFAULT_MAX_DB_LOAD_SIZE" : 500000,
        "_DEFAULT_BASE_DIRECTORY" : 'Dataflows',
        "_DEFAULT_MEMORY_MODE" : 'low',
        "_DEFAULT_DISK_MODE" : 'low',
        "_DEFAULT_OUTPUT_MODE" : 'notebook',

        "DEFAULT_BASE_PATH" : '.',
        "DEFAULT_TEMPFILE" : 'temp',
        "DEFAULT_LOGFILE" : 'dsphere.status_log.txt',
        "DEFAULT_LOGS_FOLDER" : '_logs',
        "DEFAULT_FLOWS_FOLDER" : "_flows",
        "DEFAULT_CONFIG_FILE" : 'dsphere.config.json',
        "DEFAULT_BASE_PATH_CONFIG_VAR" : "base_folder",
        "DEFAULT_TEMP_FILE_CONFIG_VAR" : "temp_file",
        "DEFAULT_DATAFLOWS_CONFIG_VAR" : "dataflows",
        "DEFAULT_FLOWS_PATH_CONFIG_VAR" : "flows_folder",
        "DEFAULT_ALERTS_CONFIG_VAR" : "alerts",
        "DEFAULT_PARAMETERS_CONFIG_VAR" : "featurespace",
        "DEFAULT_STREAMS_CONFIG_VAR" : "streams",
        "DEFAULT_STREAMS_SCHEDULE_VAR" : "schedule",
        "DEFAULT_STREAMS_EXECUTOR_VAR" : "executors",
        "DEFAULT_CONNECTORS_CONFIG_VAR" : "connectors", 
        "DEFAULT_SYNCS_CONFIG_VAR" : "syncs",
        "DEFAULT_MODELERS_CONFIG_VAR" : "modelers",
        "DEFAULT_ARCHIVE_COMMAND" : "archive",
    }
    