repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-toml
    - id: check-yaml
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
