[tool.poetry]
name = "test_day"
version = "0.1.0"
description = ""
authors = ["Stefan Hagemann <StefanHagemann@gmx.at>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.3"
matplotlib = "^3.5.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
