[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "memgen"
description = "Calls MemGen service located at http://memgen.uni-saarland.de/api"
readme = "README.md"
requires-python = ">= 3.6"
classifiers = ["Operating System :: POSIX :: Linux"]
dependencies = ['numpy']
dynamic = ["version"]

[project.optional-dependencies]
dev = ['mdanalysis', 'pytest']
local = ['acpype ~= 2022.6.6']
external = ['gmxapi', 'openbabel']

[project.scripts]
memgen = "memgen:main"

[tool.setuptools_scm]
