
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T03:19:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "14d714f4a8fe3928a6951d6528e1a21ad28e4308",
 "version": "0.2.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
