[tool.poetry]
name = "arcane-datastore"
version = "1.1.1"
description = "Override datastore client"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
google-cloud-datastore = "^2.5.1"
backoff = "^1.10.0"
arcane-core = "^1.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
