[tool.poetry]
name = "emgraph"
version = "1.0.0-rc1"
description = "A Python library for knowledge graph representation learning (graph embedding)"
homepage = "https://bi-graph.github.io/Emgraph"
repository = "https://github.com/bi-graph/Emgraph"
authors = ["Soran Ghaderi <soran.gdr.cd@gmail.com>", "sigma1326 <taleb.zarhesh@gmail.com>"]
maintainers = ["Soran Ghaderi <soran.gdr.cd@gmail.com>", "sigma1326 <taleb.zarhesh@gmail.com>"]
readme = "README.md"
license = "BSD"
include = [
    "License.txt",
]
packages = [
    { include = "emgraph" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules :: Deep Learning :: Graph Representation Learning :: Graph Embedding :: Graph :: Knowledge Graph",
]
keywords = [
    "tensorflow",
    "python",
    "graph",
    "knowledge graph",
    "representation learning",
    "graph representation learning",
    "deep learning",
]

[tool.poetry.dependencies]
python = "~3.10"
tqdm = "^4.64.0"
numpy = "^1.23.1"
pandas = "^1.4.3"
scipy = "^1.9.0"
#sklearn = "^0.0"
tensorflow-gpu = { path = "tensorflow_gpu-2.8.0-cp310-cp310-manylinux2010_x86_64.whl" }
#torch = { path = "torch-1.11.0+cu115-cp310-cp310-linux_x86_64.whl" }
#networkx = "^2.8.1"
pytest = "^7.1.2"
rdflib = "^6.2.0"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
