VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('01')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('36')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202208011136
version_date = '2022/08/01 11:36'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
