[build-system]
requires = ["setuptools>=58.1"]
build-backend = "setuptools.build_meta"

[project]
name = "snakebuild"
version = "0.0.1"
authors = [
    { name="Khyle Isaias", email="khyleisaias@gmail.com" },
]
description = "Originally named Pybuild. It is a new build system written in Python, because y not?"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/khyleisaias/pybuild"
"Bug Tracker" = "https://github.com/khyleisaias/pybuild/issues"
