[tool.poetry]
name = "pypy-geoff"
version = "0.1.3"
description = ""
authors = ["Geoff Dutton <g.dutton@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.20.0"
black = {version = "^22.6.0", allow-prereleases = true}
scriv = {extras = ["toml"], version = "^0.16.0"}
tox = "^3.25.1"
coverage = "^6.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.scriv]
format = "md"
