[project]
name = "NightBat"
version = "0.0.1"
authors = [
  { name="Nong Hoang Vu", email="nonghoangvu04@gmail.com" },
]
description = "NightBat"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Server04/NightBat"
"Bug Tracker" = "https://github.com/Server04/NightBat"