
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-31T22:24:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d1b65ee691de7be281cdd6e898b38e5ad95e17a",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
