[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "talonfmt"
version = "1.3.0"
description = "A code formatter for Talon files"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["talonfmt"]
authors = [{ name = "Wen Kokke" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
]
dependencies = [
  "click >= 8, <= 9",
  "tree_sitter_talon >= 1.5.3",
  "doc_printer >= 0.9.0"
]

[project.optional-dependencies]
test = ["pytest", "pytest-golden"]
publish = ["build", "twine"]

[project.urls]
repository = "https://github.com/wenkokke/talonfmt"

[project.scripts]
talonfmt = "talonfmt:cli"

[tool.setuptools.package-data]
talonfmt = ["py.typed"]

[pytest]
testpaths = "test"

[tool.pytest.ini_options]
enable_assertion_pass_hook = true
filterwarnings = ["ignore::DeprecationWarning:.*:"]

[tool.bumpver]
current_version = "1.3.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
