"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class OrganizationInvite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    ACTIVATION_LINK_FIELD_NUMBER: builtins.int
    INVITER_NAME_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.OrganizationInviteId: ...
    @property
    def organization_id(self) -> api.ids_pb2.Auth0OrganizationId: ...
    email: typing.Text
    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.ids_pb2.RoleId]: ...
    activation_link: typing.Text
    inviter_name: typing.Text
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.OrganizationInviteId] = ...,
        organization_id: typing.Optional[api.ids_pb2.Auth0OrganizationId] = ...,
        email: typing.Text = ...,
        roles: typing.Optional[typing.Iterable[api.ids_pb2.RoleId]] = ...,
        activation_link: typing.Text = ...,
        inviter_name: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","organization_id",b"organization_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["activation_link",b"activation_link","email",b"email","id",b"id","inviter_name",b"inviter_name","organization_id",b"organization_id","roles",b"roles"]) -> None: ...
global___OrganizationInvite = OrganizationInvite
