# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toggles/toggles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from featureguards.proto.shared import feature_toggle_pb2 as shared_dot_feature__toggle__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15toggles/toggles.proto\x12\x07toggles\x1a\x1bshared/feature_toggle.proto\"P\n\x0c\x46\x65tchRequest\x12/\n\x08platform\x18\x01 \x01(\x0e\x32\x1d.feature_toggle.Platform.Type\x12\x0f\n\x07version\x18\x02 \x01(\x03\"X\n\rFetchResponse\x12\x36\n\x0f\x66\x65\x61ture_toggles\x18\x01 \x03(\x0b\x32\x1d.feature_toggle.FeatureToggle\x12\x0f\n\x07version\x18\x02 \x01(\x03\"Q\n\rListenRequest\x12/\n\x08platform\x18\x01 \x01(\x0e\x32\x1d.feature_toggle.Platform.Type\x12\x0f\n\x07version\x18\x02 \x01(\x03\"X\n\rListenPayload\x12\x36\n\x0f\x66\x65\x61ture_toggles\x18\x01 \x03(\x0b\x32\x1d.feature_toggle.FeatureToggle\x12\x0f\n\x07version\x18\x02 \x01(\x03\x32\x81\x01\n\x07Toggles\x12\x38\n\x05\x46\x65tch\x12\x15.toggles.FetchRequest\x1a\x16.toggles.FetchResponse\"\x00\x12<\n\x06Listen\x12\x16.toggles.ListenRequest\x1a\x16.toggles.ListenPayload\"\x00\x30\x01\x42<Z:github.com/featureguards/featureguards-go/v2/proto/togglesb\x06proto3'
)

_FETCHREQUEST = DESCRIPTOR.message_types_by_name['FetchRequest']
_FETCHRESPONSE = DESCRIPTOR.message_types_by_name['FetchResponse']
_LISTENREQUEST = DESCRIPTOR.message_types_by_name['ListenRequest']
_LISTENPAYLOAD = DESCRIPTOR.message_types_by_name['ListenPayload']
FetchRequest = _reflection.GeneratedProtocolMessageType(
    'FetchRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _FETCHREQUEST,
        '__module__': 'toggles.toggles_pb2'
        # @@protoc_insertion_point(class_scope:toggles.FetchRequest)
    })
_sym_db.RegisterMessage(FetchRequest)

FetchResponse = _reflection.GeneratedProtocolMessageType(
    'FetchResponse',
    (_message.Message, ),
    {
        'DESCRIPTOR': _FETCHRESPONSE,
        '__module__': 'toggles.toggles_pb2'
        # @@protoc_insertion_point(class_scope:toggles.FetchResponse)
    })
_sym_db.RegisterMessage(FetchResponse)

ListenRequest = _reflection.GeneratedProtocolMessageType(
    'ListenRequest',
    (_message.Message, ),
    {
        'DESCRIPTOR': _LISTENREQUEST,
        '__module__': 'toggles.toggles_pb2'
        # @@protoc_insertion_point(class_scope:toggles.ListenRequest)
    })
_sym_db.RegisterMessage(ListenRequest)

ListenPayload = _reflection.GeneratedProtocolMessageType(
    'ListenPayload',
    (_message.Message, ),
    {
        'DESCRIPTOR': _LISTENPAYLOAD,
        '__module__': 'toggles.toggles_pb2'
        # @@protoc_insertion_point(class_scope:toggles.ListenPayload)
    })
_sym_db.RegisterMessage(ListenPayload)

_TOGGLES = DESCRIPTOR.services_by_name['Toggles']
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z:github.com/featureguards/featureguards-go/v2/proto/toggles'
    _FETCHREQUEST._serialized_start = 63
    _FETCHREQUEST._serialized_end = 143
    _FETCHRESPONSE._serialized_start = 145
    _FETCHRESPONSE._serialized_end = 233
    _LISTENREQUEST._serialized_start = 235
    _LISTENREQUEST._serialized_end = 316
    _LISTENPAYLOAD._serialized_start = 318
    _LISTENPAYLOAD._serialized_end = 406
    _TOGGLES._serialized_start = 409
    _TOGGLES._serialized_end = 538
# @@protoc_insertion_point(module_scope)
