[tool.poetry]
name = "picsellia-connexion-services"
version = "0.1.0"
description = "Package for connection to Picsellia platforms with some wrapper around requests library"
authors = ["Thomas Darget <thomasdarget@hotmail.fr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
coverage = "5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
