[build-system]
requires = ["setuptools>=63.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pmgslack"
version = "0.0.1"
description = "PMG+ Slack Integration Tools"
readme = "README.md"
authors = [{ name = "Preston Meyer Group", email = "dev@pmgroup.ch" }]
license = { text = "MIT" }
classifiers = [
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License"
]
keywords = ["tools", "utils"]
dependencies = []
requires-python = ">=3.9"

[project.optional-dependencies]
test = [
    "pytest",
    "hypothesis",
]