[tool.poetry]
name = "ifood-ds-utils"
version = "0.2"
description = ""
authors = ["Javier Daza <javier.olivella@ifood.com>"]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.5"
ifood-aws-login = "^0.0.1"
click = "^8.1.3"
directory-tree = "^0.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mlgo_template = "ifood_ds_utils.main:create_ifood_mlgo_template"
s3_template = "ifood_ds_utils.main:create_ifood_s3_template"
upload-folder-s3 = "ifood_ds_utils.main:upload_to_s3"
ifood-ds-utils = "ifood_ds_utils.main:version"