---

- name: Start the container
  community.docker.docker_container:
    name: rest-api
    image: ghcr.io/autoreduction/autoreduce-rest-api:latest
    state: started
    pull: true
    env:
      AUTOREDUCTION_PRODUCTION: "true"
    volumes:
      - /home/{{ autoreduction_user }}/.autoreduce:/home/{{ autoreduction_user }}/.autoreduce:rw
      - /instrument:/instrument:rw
      - /isis:/isis
      - /shared-config:/shared-config
    network_mode: host
    detach: yes
    comparisons:
      image: strict
