[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Indonesia-earthquakeliveinfo"
version = "0.9"
authors = [
  { name="Muchamad Faiz", email="muchamadfaiz@gmail.com" },
]
description = "Package content with beautifulsoup4 and requests, from JSON can be used on mobile & web applications"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]

[project.urls]
"Homepage" = "https://github.com/muchamadfaiz/latest-indonesia-earthquake"
#"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"