[tool.poetry]
name = "task-flows"
version = "0.2.6"
description = ""
authors = ["Dan <kelleherjdan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
alert-msgs = "^0.1.0"
SQLAlchemy = "^1.4.35"
psycopg = {version= "^3.0.15",  extras=["c"]}
docker = "^5.0.3"
tqdm = "^4.64.0"
click = "^8.1.3"
ready-logger = "^0.1.4"
python-dotenv = "^0.20.0"
dynamic-imports = "^0.1.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tasks = 'task_flows.admin:cli'
