[build-system]
requires = ["setuptools>=51.0", "rich", "requests"]
build-backend = "setuptools.build_meta"

[project]
name = "sw6_api"
version = "1.0.2"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "6_API"
requires-python = ">=3.7"
