# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7

services:
  - docker

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

before_install:
  - docker pull influxdb
  - docker run -d -p 8086:8086 -v influxdb:/var/lib/influxdb influxdb:1.7.6-alpine

script:
  - python setup.py test
  - make linkcheck
  - make docs

after_success:
  - pip install ltd-conveyor==0.5.0a1
  - 'ltd upload --product "efd-client" --travis --dir doc/_build/html'

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: cRBQmVUEE7/zd5JmKKzJfEEtG0oxuriX5yNCwn99iLZvj9BMvoCPq4P7q9zpujuCqVwGfTzbvnzxFx0VOP57vKggfQsJugTmY66psC1yoDxKj3OZIJ1nbpLPzqJdsBb/uIeV8xVNiHY5aFIxkNEqO1JNb8mzz+YF6Kz6eTywzkEEhddkeoRNlmjXW77W5wQ2CMjLAZOhpxP4FpgCVCm5xGievSJXi7Otwx8yRacXij3unFZvjgpF3TBLXCIdk8YB26BbN/jmMHIRywq2yZ7O9aD3lbvoTfwjnL+XDeXTbwn0useG/5mGIkc6JVnYPfCx6c5lV+FdoDqsNSIhfOcLMBlTYPVWfnMV+XpFlTwYHrRST6kBIU8dZe/7erjBB+1vFedoDhntx175b2/d9+QAcFu4kpaQL+/HIsArdlldBWapqwp71yB2L7GNTm4qyBzW5bSWvsW+S3ysACr0xfe7OHuDlfWq/tAujjTCHreyNufUWsDRC3l4ZX+Dj5ITmj7dhpYPVUNIyciONFZ4FYvY5zvBMRLtBmwM8J3ypUewHMFg86f2CvkJC/wxXITaOta0y2wZ181OixL32IvxtFX8KbllU8vC9M293q39nDH3EOXDkzzG1WDvnhOWtK3WYslxbdSlHdX//U3bUlvn5yBtszgCaAUAolCitHBYe9/8bTA=
  on:
    tags: true
    repo: lsst-sqre/lsst-efd-client
    python: 3.7

env:
  global:
    # LSST the Docs credentials
    - secure: "Su0VSKCFW8cPdgCmJx+JP62B0LtDq6lrZvVldtUloO/r4r/w8REmFlJWT27p+dhWEOFKA1n0jrNsKHMrL9nit0nPyF28imFX1tzd2KRHNZ8GAE+fuzfyf3D6Lkd7zoXZ5HiE5eZg5NdF3QUSXdZxv2PZzWbv/egU460h8dvD5K+3m8sypxhbHf6snOzBlFIEKTBlza2uiWxkm2Y9fUv2511kAYmr3WrAYqTbgPM1LKIp6EaC81PwEhqcclnb6FGGW3FhHGOHX49hABkHea8cooStEAr6mFzHvsLyTX5vfPLmBrPfWTTPMyXHOJj4Csuy1RdP47bedt8/VZcxQ3e4meBwmXg0JqiGfAc5HKqMPJGpnja3iFsrrOiPFYCDxdQlNcGfW/3Rhmy4rtixxrw0Eho+gMBQB52F8MuFH/8Ngi1wp5Sbm9TpYc1Yn/taIAPBBHmCUIAra845bnvQY8b3nyxYAsGLfc8S1B1DbbYUQdBpage2Hap2JifIqPZdlPkheLdBp9GargvopTvL01HMxhw3YB6O4FMr/4nz+OdpbxHwmIPApM4q1jMUU3BlQj4XD5OZHn19YWRZVc7agZdm76ftBm0fbQNlbA9agRSJdGHswA6nIGo2ApTbz9RJgoCC68vRLm1g/p7DeKLzPTUU0Whrx873s5qDMNnGYXcOsx8="
