
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-01T10:09:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "637c74ad60004887522f7bd3fa97a7dfd221839b",
 "version": "v0.7.0a.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
