
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T13:15:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fac3bdcdfb40e5d39e4b88d4f4d9e1910e38dc88",
 "version": "0.5.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
