[tool.poetry]
name = "switchforpython"
version = "0.1.2"
description = "Switch statements in python 3.x"
authors = ["Python Nerd <prajwalmisc@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
