
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T20:51:34+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3485e78847265af386d19526106d9b04ab6be0f",
 "version": "1.5.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
