
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T09:04:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd8ae1c33002c6029c1e4df9380821e9395d00e7",
 "version": "2022.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
