class MetaxDisabledError(Exception):...

class RequestTypeError(Exception):...

class GettingFileFiledError(Exception):...

class InvalidUUIDError(Exception):...

class ResponseError(Exception):...

class DecryptionFailedError(Exception):...

class MetaxRequestException(Exception):...

class FileSaveError(Exception):...

class UnknownUUIDError(Exception):...

class ShareArgumentsError(Exception):...