[project]
name = "badrandom"
version = "0.0.1"
authors = [
    { name = "Rob Hagemans", email = "rob.hagemans@hotmail.com" },
]
description = "An implementation of the bad random number generator used in legacy Microsoft BASIC. Do not use to generate random numbers."
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Topic :: System :: Emulators",
    "Topic :: Scientific/Engineering :: Mathematics",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
]
keywords = [
    "random", "legacy", "compatibility",
]

[project.urls]
"Homepage" = "http://pc-basic.org"

