[tool.poetry]
name = "alert_msgs"
version = "0.1.0"
description = "Utilities for creating HTML and Markdown alert messages."
authors = ["Dan Kelleher <kelleherjdan@gmail.com>"]
include = ["alert_msgs/styles/*"]


[tool.poetry.dependencies]
python = "^3.9"
ready-logger = "^0.1.3"
pydantic = "^1.9.0"
premailer = "^3.10.0"
dominate = "^2.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pylama = {extras = ["all"], version = "^8.3.6"}
black = "^21.12b0"
jupyter = "^1.0.0"
python-dotenv = "^0.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

