[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "databridges_nacl_wrapper"
authors = [{name = "Optomate Technologies Private Limited.", email = "tech@optomate.io"}]
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["optomate","databridges","pubsub","rpc","websocket","socket.io","ws","events","realtime","real-time","nacl","encryption"]
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "PyNaCl==1.5.0",
]

[project.urls]
Documentation = "https://github.com/databridges-io/lib.python.nacl.wrapper"
Source = "https://github.com/databridges-io/lib.python.nacl.wrapper"
