[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''(
/(
  | \.direnv
  | \.eggs
  | \.git
  | \.venv
  | _build
  | build
  | dist
)/
)
'''