# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scope_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1045, 793)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.offsetLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.offsetLayout.setContentsMargins(0, 0, 0, 0)
        self.offsetLayout.setSpacing(3)
        self.offsetLayout.setObjectName("offsetLayout")
        self.slider1 = QtWidgets.QSlider(self.frame_2)
        self.slider1.setStyleSheet("")
        self.slider1.setMinimum(-4)
        self.slider1.setMaximum(4)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.offsetLayout.addWidget(self.slider1)
        self.slider2 = QtWidgets.QSlider(self.frame_2)
        self.slider2.setStyleSheet("")
        self.slider2.setMinimum(-4)
        self.slider2.setMaximum(4)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.offsetLayout.addWidget(self.slider2)
        self.slider3 = QtWidgets.QSlider(self.frame_2)
        self.slider3.setStyleSheet("")
        self.slider3.setMinimum(-4)
        self.slider3.setMaximum(4)
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setObjectName("slider3")
        self.offsetLayout.addWidget(self.slider3)
        self.slider4 = QtWidgets.QSlider(self.frame_2)
        self.slider4.setStyleSheet("")
        self.slider4.setMinimum(-4)
        self.slider4.setMaximum(4)
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setObjectName("slider4")
        self.offsetLayout.addWidget(self.slider4)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.Diff = QtWidgets.QCheckBox(Form)
        self.Diff.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Diff.setObjectName("Diff")
        self.gridLayout.addWidget(self.Diff, 1, 3, 1, 1)
        self.Freeze = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Freeze.sizePolicy().hasHeightForWidth())
        self.Freeze.setSizePolicy(sizePolicy)
        self.Freeze.setObjectName("Freeze")
        self.gridLayout.addWidget(self.Freeze, 1, 4, 1, 1)
        self.Cross = QtWidgets.QCheckBox(Form)
        self.Cross.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Cross.setObjectName("Cross")
        self.gridLayout.addWidget(self.Cross, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pwinview = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwinview.sizePolicy().hasHeightForWidth())
        self.pwinview.setSizePolicy(sizePolicy)
        self.pwinview.setMinimumSize(QtCore.QSize(30, 0))
        self.pwinview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pwinview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pwinview.setObjectName("pwinview")
        self.plotLayout = QtWidgets.QHBoxLayout(self.pwinview)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 1, 1, 4)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 15, 1, 1, 3)
        self.FREQ = QtWidgets.QPushButton(self.frame)
        self.FREQ.setObjectName("FREQ")
        self.gridLayout_2.addWidget(self.FREQ, 5, 1, 1, 4)
        self.RES = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RES.sizePolicy().hasHeightForWidth())
        self.RES.setSizePolicy(sizePolicy)
        self.RES.setObjectName("RES")
        self.gridLayout_2.addWidget(self.RES, 3, 1, 1, 4)
        self.CAP = QtWidgets.QPushButton(self.frame)
        self.CAP.setObjectName("CAP")
        self.gridLayout_2.addWidget(self.CAP, 4, 1, 1, 4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 15, 4, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_6.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_6.setSizePolicy(sizePolicy)
        self.horizontalSlider_6.setMinimum(-3300)
        self.horizontalSlider_6.setMaximum(3300)
        self.horizontalSlider_6.setProperty("value", 99)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.gridLayout_5.addWidget(self.horizontalSlider_6, 1, 3, 1, 1)
        self.trigBox = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trigBox.sizePolicy().hasHeightForWidth())
        self.trigBox.setSizePolicy(sizePolicy)
        self.trigBox.setMaximumSize(QtCore.QSize(55, 16777215))
        self.trigBox.setObjectName("trigBox")
        self.gridLayout_5.addWidget(self.trigBox, 1, 2, 1, 1)
        self.TBslider = QtWidgets.QSlider(self.frame_6)
        self.TBslider.setMaximum(8)
        self.TBslider.setPageStep(1)
        self.TBslider.setProperty("value", 1)
        self.TBslider.setOrientation(QtCore.Qt.Horizontal)
        self.TBslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.TBslider.setObjectName("TBslider")
        self.gridLayout_5.addWidget(self.TBslider, 0, 1, 1, 3)
        self.trigEnable = QtWidgets.QCheckBox(self.frame_6)
        self.trigEnable.setChecked(True)
        self.trigEnable.setObjectName("trigEnable")
        self.gridLayout_5.addWidget(self.trigEnable, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 14, 1, 1, 4)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 11, 1, 1, 4)
        self.OD1 = QtWidgets.QCheckBox(self.frame)
        self.OD1.setObjectName("OD1")
        self.gridLayout_2.addWidget(self.OD1, 7, 1, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.A1Box = QtWidgets.QCheckBox(self.frame_4)
        self.A1Box.setObjectName("A1Box")
        self.gridLayout_4.addWidget(self.A1Box, 0, 0, 1, 1)
        self.IN2Box = QtWidgets.QCheckBox(self.frame_4)
        self.IN2Box.setObjectName("IN2Box")
        self.gridLayout_4.addWidget(self.IN2Box, 4, 0, 1, 1)
        self.IN2Range = QtWidgets.QComboBox(self.frame_4)
        self.IN2Range.setObjectName("IN2Range")
        self.gridLayout_4.addWidget(self.IN2Range, 4, 1, 1, 1)
        self.IN1Box = QtWidgets.QCheckBox(self.frame_4)
        self.IN1Box.setObjectName("IN1Box")
        self.gridLayout_4.addWidget(self.IN1Box, 3, 0, 1, 1)
        self.IN1Range = QtWidgets.QComboBox(self.frame_4)
        self.IN1Range.setObjectName("IN1Range")
        self.gridLayout_4.addWidget(self.IN1Range, 3, 1, 1, 1)
        self.A2Range = QtWidgets.QComboBox(self.frame_4)
        self.A2Range.setObjectName("A2Range")
        self.gridLayout_4.addWidget(self.A2Range, 1, 1, 1, 1)
        self.A2Box = QtWidgets.QCheckBox(self.frame_4)
        self.A2Box.setObjectName("A2Box")
        self.gridLayout_4.addWidget(self.A2Box, 1, 0, 1, 1)
        self.A1Range = QtWidgets.QComboBox(self.frame_4)
        self.A1Range.setObjectName("A1Range")
        self.gridLayout_4.addWidget(self.A1Range, 0, 1, 1, 1)
        self.IN1Fit = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IN1Fit.sizePolicy().hasHeightForWidth())
        self.IN1Fit.setSizePolicy(sizePolicy)
        self.IN1Fit.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.IN1Fit.setFont(font)
        self.IN1Fit.setText("")
        self.IN1Fit.setObjectName("IN1Fit")
        self.gridLayout_4.addWidget(self.IN1Fit, 3, 2, 1, 1)
        self.IN2Fit = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IN2Fit.sizePolicy().hasHeightForWidth())
        self.IN2Fit.setSizePolicy(sizePolicy)
        self.IN2Fit.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.IN2Fit.setFont(font)
        self.IN2Fit.setText("")
        self.IN2Fit.setObjectName("IN2Fit")
        self.gridLayout_4.addWidget(self.IN2Fit, 4, 2, 1, 1)
        self.A2Fit = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A2Fit.sizePolicy().hasHeightForWidth())
        self.A2Fit.setSizePolicy(sizePolicy)
        self.A2Fit.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.A2Fit.setFont(font)
        self.A2Fit.setText("")
        self.A2Fit.setObjectName("A2Fit")
        self.gridLayout_4.addWidget(self.A2Fit, 1, 2, 1, 1)
        self.A1Fit = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1Fit.sizePolicy().hasHeightForWidth())
        self.A1Fit.setSizePolicy(sizePolicy)
        self.A1Fit.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.A1Fit.setFont(font)
        self.A1Fit.setText("")
        self.A1Fit.setObjectName("A1Fit")
        self.gridLayout_4.addWidget(self.A1Fit, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 12, 1, 1, 4)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.voltMeterIN1 = QtWidgets.QCheckBox(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.voltMeterIN1.setFont(font)
        self.voltMeterIN1.setObjectName("voltMeterIN1")
        self.horizontalLayout.addWidget(self.voltMeterIN1)
        self.voltMeterIN2 = QtWidgets.QCheckBox(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.voltMeterIN2.setFont(font)
        self.voltMeterIN2.setObjectName("voltMeterIN2")
        self.horizontalLayout.addWidget(self.voltMeterIN2)
        self.gridLayout_2.addWidget(self.frame_7, 2, 1, 1, 4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SQ1Label = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQ1Label.sizePolicy().hasHeightForWidth())
        self.SQ1Label.setSizePolicy(sizePolicy)
        self.SQ1Label.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SQ1Label.setFont(font)
        self.SQ1Label.setObjectName("SQ1Label")
        self.gridLayout_3.addWidget(self.SQ1Label, 1, 0, 1, 1)
        self.PV1slider = QtWidgets.QSlider(self.frame_3)
        self.PV1slider.setMinimum(0)
        self.PV1slider.setMaximum(5000)
        self.PV1slider.setProperty("value", 0)
        self.PV1slider.setOrientation(QtCore.Qt.Horizontal)
        self.PV1slider.setObjectName("PV1slider")
        self.gridLayout_3.addWidget(self.PV1slider, 2, 1, 1, 2)
        self.PV1text = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.PV1text.setMaximumSize(QtCore.QSize(150, 16777215))
        self.PV1text.setMinimum(0.0)
        self.PV1text.setMaximum(5.0)
        self.PV1text.setObjectName("PV1text")
        self.gridLayout_3.addWidget(self.PV1text, 2, 3, 1, 2)
        self.PV1Label = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PV1Label.sizePolicy().hasHeightForWidth())
        self.PV1Label.setSizePolicy(sizePolicy)
        self.PV1Label.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PV1Label.setFont(font)
        self.PV1Label.setObjectName("PV1Label")
        self.gridLayout_3.addWidget(self.PV1Label, 2, 0, 1, 1)
        self.SQ1text = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.SQ1text.setMaximumSize(QtCore.QSize(150, 16777215))
        self.SQ1text.setMinimum(0.0)
        self.SQ1text.setMaximum(5000.0)
        self.SQ1text.setObjectName("SQ1text")
        self.gridLayout_3.addWidget(self.SQ1text, 0, 3, 1, 2)
        self.WGLabel = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WGLabel.sizePolicy().hasHeightForWidth())
        self.WGLabel.setSizePolicy(sizePolicy)
        self.WGLabel.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.WGLabel.setFont(font)
        self.WGLabel.setObjectName("WGLabel")
        self.gridLayout_3.addWidget(self.WGLabel, 0, 0, 1, 1)
        self.SQ1slider = QtWidgets.QSlider(self.frame_3)
        self.SQ1slider.setMinimum(0)
        self.SQ1slider.setMaximum(5000)
        self.SQ1slider.setOrientation(QtCore.Qt.Horizontal)
        self.SQ1slider.setObjectName("SQ1slider")
        self.gridLayout_3.addWidget(self.SQ1slider, 0, 1, 1, 2)
        self.SQ2text = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.SQ2text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SQ2text.setMaximum(5000.0)
        self.SQ2text.setObjectName("SQ2text")
        self.gridLayout_3.addWidget(self.SQ2text, 1, 4, 1, 1)
        self.SQ2slider = QtWidgets.QSlider(self.frame_3)
        self.SQ2slider.setMinimum(0)
        self.SQ2slider.setMaximum(5000)
        self.SQ2slider.setProperty("value", 0)
        self.SQ2slider.setSliderPosition(0)
        self.SQ2slider.setOrientation(QtCore.Qt.Horizontal)
        self.SQ2slider.setObjectName("SQ2slider")
        self.gridLayout_3.addWidget(self.SQ2slider, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 9, 1, 2, 4)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 8, 1, 1, 4)
        self.CCS = QtWidgets.QCheckBox(self.frame)
        self.CCS.setObjectName("CCS")
        self.gridLayout_2.addWidget(self.CCS, 7, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 3)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.voltMeterA1 = QtWidgets.QCheckBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.voltMeterA1.setFont(font)
        self.voltMeterA1.setObjectName("voltMeterA1")
        self.horizontalLayout_2.addWidget(self.voltMeterA1)
        self.voltMeterA2 = QtWidgets.QCheckBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.voltMeterA2.setFont(font)
        self.voltMeterA2.setObjectName("voltMeterA2")
        self.horizontalLayout_2.addWidget(self.voltMeterA2)
        self.gridLayout_2.addWidget(self.frame_8, 1, 1, 1, 4)
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 4)
        self.msgwin = QtWidgets.QLabel(Form)
        self.msgwin.setObjectName("msgwin")
        self.gridLayout.addWidget(self.msgwin, 1, 0, 1, 2)

        self.retranslateUi(Form)
        self.IN2Range.setCurrentIndex(-1)
        self.IN1Range.setCurrentIndex(-1)
        self.A2Range.setCurrentIndex(-1)
        self.A1Range.setCurrentIndex(-1)
        self.pushButton_5.clicked.connect(Form.show_fft)
        self.pushButton_4.clicked.connect(Form.save_data)
        self.PV1text.editingFinished.connect(Form.pv1_text)
        self.PV1slider.valueChanged['int'].connect(Form.pv1_slider)
        self.TBslider.valueChanged['int'].connect(Form.set_timebase)
        self.trigBox.currentIndexChanged['int'].connect(Form.select_trig_source)
        self.horizontalSlider_6.valueChanged['int'].connect(Form.set_trigger)
        self.SQ1slider.valueChanged['int'].connect(Form.sq1_slider)
        self.SQ1text.editingFinished.connect(Form.sq1_text)
        self.SQ2slider.valueChanged['int'].connect(Form.sq2_slider)
        self.SQ2text.editingFinished.connect(Form.sq2_text)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Diff.setText(_translate("Form", "A2-A1"))
        self.Freeze.setText(_translate("Form", "FREEZE"))
        self.Cross.setText(_translate("Form", "Cursor"))
        self.pushButton_4.setText(_translate("Form", "SAVE Traces"))
        self.FREQ.setText(_translate("Form", "Frequency (IN2):"))
        self.RES.setText(_translate("Form", "Resistance on SEN"))
        self.CAP.setText(_translate("Form", "Capacitance (IN1):"))
        self.pushButton_5.setText(_translate("Form", "Fourier Transform"))
        self.label_5.setText(_translate("Form", "Timebase"))
        self.trigEnable.setText(_translate("Form", "Trigger"))
        self.OD1.setText(_translate("Form", "OD1"))
        self.A1Box.setText(_translate("Form", "A1"))
        self.IN2Box.setText(_translate("Form", "IN2"))
        self.IN1Box.setText(_translate("Form", "IN1"))
        self.A2Box.setText(_translate("Form", "A2"))
        self.IN1Fit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Amplitude</span> and <span style=\" font-weight:600;\">frequency</span> extracted from the</p><p>sinusoidal signal using least square fitting.</p><p><br/></p><p>This assumes a sine wave input is provided.</p><p><br/></p><p>For mixed signals, use the FOURIER transform button</p><p>below.</p></body></html>"))
        self.IN2Fit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Amplitude</span> and <span style=\" font-weight:600;\">frequency</span> extracted from the</p><p>sinusoidal signal using least square fitting.</p><p><br/></p><p>This assumes a sine wave input is provided.</p><p><br/></p><p>For mixed signals, use the FOURIER transform button</p><p>below.</p></body></html>"))
        self.A2Fit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Amplitude</span> and <span style=\" font-weight:600;\">frequency</span> extracted from the</p><p>sinusoidal signal using least square fitting.</p><p><br/></p><p>This assumes a sine wave input is provided.</p><p><br/></p><p>For mixed signals, use the FOURIER transform button</p><p>below.</p></body></html>"))
        self.A1Fit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Amplitude</span> and <span style=\" font-weight:600;\">frequency</span> extracted from the</p><p>sinusoidal signal using least square fitting.</p><p><br/></p><p>This assumes a sine wave input is provided.</p><p><br/></p><p>For mixed signals, use the FOURIER transform button</p><p>below.</p></body></html>"))
        self.voltMeterIN1.setText(_translate("Form", "IN1"))
        self.voltMeterIN2.setText(_translate("Form", "IN2"))
        self.SQ1Label.setText(_translate("Form", "SQ2"))
        self.PV1slider.setProperty("class", _translate("Form", "symmetric volts"))
        self.PV1text.setSuffix(_translate("Form", " Volts"))
        self.PV1Label.setText(_translate("Form", "PVS"))
        self.SQ1text.setSuffix(_translate("Form", " Hz"))
        self.WGLabel.setText(_translate("Form", "SQ1"))
        self.SQ1slider.setProperty("class", _translate("Form", "symmetric"))
        self.SQ2text.setSuffix(_translate("Form", " Hz"))
        self.SQ2slider.setProperty("class", _translate("Form", "symmetric"))
        self.CCS.setText(_translate("Form", "CCS"))
        self.label_4.setText(_translate("Form", "Measure Voltages"))
        self.voltMeterA1.setText(_translate("Form", "A1"))
        self.voltMeterA2.setText(_translate("Form", "A2"))
        self.msgwin.setText(_translate("Form", "."))
