[project]
name = "django-subdomains2"
version = "4.0.0"
authors = [{ name = "lhy", email = "dev@lhy.kr" }]
description = "Subdomain tools for the Django framework, including subdomain-based URL routing."
readme = "README.rst"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Programming Language :: Python",
]
dependencies = [
    "django",
]

[project.urls]
"GitHub" = "https://github.com/LeeHanYeong/django-subdomains"

[tool.setuptools.packages.find]
where = []
include = ["subdomains"]  # alternatively: `exclude = ["additional*"]`
namespaces = false

[tool.black]
line-length = 130
