[project]
name = "basicsound"
version = "0.0.1"
authors = [
    { name = "Rob Hagemans", email = "rob.hagemans@hotmail.com" },
]
description = "Sound synthesizer that plays multivoice sound by frequency, duration and volume, or through ANSI music/music markup language."
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Topic :: System :: Emulators",
    "Topic :: Scientific/Engineering :: Mathematics",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
]
keywords = [
    "sound", "audio", "ansi music"
]

[project.urls]
"Homepage" = "http://pc-basic.org"

