
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T12:32:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d98a072278434747c199504f09a5fa972f40e30",
 "version": "2.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
