[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jquants-api-client"
version = "0.0.1"
authors = [
  { name="J-Quants Project Contributors", email="j-quants@jpx.co.jp" },
]
description = "J-Quants API Client Library"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/J-Quants/jquants-api-client-python"
"Bug Tracker" = "https://github.com/J-Quants/jquants-api-client-python/issues"
