[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "meteo_hr"
version = "0.1.0"
authors = [{ name="Ivan Habunek", email="ivan@habunek.com" }]
description = "CLI for printing weather forecast from meteo.hr"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Environment :: Console",
]

[project.urls]
"Homepage" = "https://git.sr.ht/~ihabunek/meteo_hr"

[console_scripts]
meteo = "meteo_hr.cli:main"
