[tool.poetry]
name = "pyadb-gui"
version = "1.2.4"
description = "Operate Android devices with a GUI tool producted by Python."
authors = ["xq <xq_work@outlook.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
rich = "^12.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[tool.poetry.scripts]
pyadb = "pyadb_gui.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
