[tool.poetry]
name = "pycellslib"
version = "0.1.0"
description = "Library for simulation and visualization of any cellular automata"
authors = ["Luis Papiernik <lpapiernik24@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "^1.23.1"
matplotlib = "^3.5.2"
pygame = "^2.1.2"
scipy = "^1.8"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
