# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\.\couchbase_version.py
# at
#    2022-08-02 17:19:16.428769
__version__ = '4.0.3'