[project]
name = "utilitycloud"
version = "0.0.3"
authors = [
  { name="Andy Crawford", email="andy.crawford@utilitycloud.us" },
  { name="Romario Jashari", email="romario.jashari@utilitycloud.us" },
]
description = "Utility Cloud Python Library"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://bitbucket.org/romariojashari/uc/src/master/"
"Bug Tracker" = "https://bitbucket.org/romariojashari/uc/src/master/"