[project]
name = "napari-allencell-annotator"
version = "0.0.1"
description = ""
readme = "README.md"
authors = [{name= "Brian Kim", email = "brian.kim@alleninstitute.org"},
    {name = "Beatrice Bridge", email = "beatrice.bridge@alleninstitute.org"}
]
license = {file = "LICENSE"}
requires-python = ">=3.7"

[tool.black]
line-length = 120
