
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T12:24:36+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "a29b8e3959e7d56964aa69786dd0e0e5063e51cb",
 "version": "2.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
