
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T14:17:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "78f6f0ceba7d759e1101e0b52f6adbd1b7329a98",
 "version": "0.4.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
