[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "exceptiongroups"
authors = [{name = "Thomas Grainger", email = "exceptiongroup@graingert.co.uk"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = ["exceptiongroup"]

[project.urls]
Home = "https://pypi.org/project/exceptiongroup/"
