[project]
name = "metax_api"
version = "0.3"
authors = [
  { name="Mikhayil Martirosyan", email="mikhayil.martirosyan@realschool.am" },
]
description = "Pyhton3 api client for metax"
readme = "README.md"
requires-python = ">=3.7"
keywords=[
	"Metax",
	"Leviathan",
	"Ehayq",
	"EhayqLLC",
	"Instigate",
	"Metax.api"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" =    "https://gitlab.com/mm_arm/metax.api"
"Bug Tracker" = "https://gitlab.com/mm_arm/metax.api/issues"
