name: tests-cygwin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.10'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up target Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Cygwin
        uses: cygwin/cygwin-install-action@v2

      - name: Install nox
        run: |
            python -m pip install nox
            nox --version

      - name: Run tests
        run: nox -s test-${{ matrix.python }}

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        env:
          PYTHON: cygwin-${{ matrix.python }}
        with:
          flags: tests
          env_vars: PYTHON
          name: cygwin-${{ matrix.python }}
