[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autoexportreader"
version = "0.0.1"
authors = [
  { name="Lauri Märtin", email="Lauri.Maertin@gmail.com" },
]
description = "Koh Young 3D SPI autoexport file parser"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/blue-sleeves/autoexportreader"
"Bug Tracker" = "https://gitlab.com/blue-sleeves/autoexportreader/-/issues"