[tool.poetry]
name = "saigen_dep_test_with_poetry"
version = "0.1.0"
description = ""
authors = ["francois_saigen <francois@saigen.co.za>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.24.40"
requests = "^2.28.1"
librosa = "^0.9.2"
SoundFile = "^0.10.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
