"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.task_pb2
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetFunctionUploadPathRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PROJECT_FULL_NAME_FIELD_NUMBER: builtins.int
    FUNCTION_NAME_FIELD_NUMBER: builtins.int
    project_full_name: typing.Text
    """With account name first e.g. "acc-name/proj-name" """

    function_name: typing.Text
    def __init__(self,
        *,
        project_full_name: typing.Text = ...,
        function_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["function_name",b"function_name","project_full_name",b"project_full_name"]) -> None: ...
global___GetFunctionUploadPathRequest = GetFunctionUploadPathRequest

class GetFunctionUploadPathResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FUNCTION_UPLOAD_PATH_FIELD_NUMBER: builtins.int
    function_upload_path: typing.Text
    def __init__(self,
        *,
        function_upload_path: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["function_upload_path",b"function_upload_path"]) -> None: ...
global___GetFunctionUploadPathResponse = GetFunctionUploadPathResponse

class GetFunctionDownloadPathRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PROJECT_FULL_NAME_FIELD_NUMBER: builtins.int
    FUNCTION_NAME_FIELD_NUMBER: builtins.int
    project_full_name: typing.Text
    """With account name first e.g. "acc-name/proj-name" """

    function_name: typing.Text
    def __init__(self,
        *,
        project_full_name: typing.Text = ...,
        function_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["function_name",b"function_name","project_full_name",b"project_full_name"]) -> None: ...
global___GetFunctionDownloadPathRequest = GetFunctionDownloadPathRequest

class GetFunctionDownloadPathResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FUNCTION_DOWNLOAD_PATH_FIELD_NUMBER: builtins.int
    function_download_path: typing.Text
    def __init__(self,
        *,
        function_download_path: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["function_download_path",b"function_download_path"]) -> None: ...
global___GetFunctionDownloadPathResponse = GetFunctionDownloadPathResponse

class ExecuteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class EnvVariablesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        value: typing.Text
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ASSET_NAME_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    FABRIC_FIELD_NUMBER: builtins.int
    CONTAINER_IMAGE_URL_FIELD_NUMBER: builtins.int
    EXECUTABLE_PACKAGE_URL_FIELD_NUMBER: builtins.int
    ENV_VARIABLES_FIELD_NUMBER: builtins.int
    asset_name: typing.Text
    """Name of the asset that this execution would produce. Will be used as a metadata key for log collection."""

    task_type: api.entity.task_pb2.Task.Type.ValueType
    @property
    def run_id(self) -> api.ids_pb2.RunId: ...
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    fabric: typing.Text
    container_image_url: typing.Text
    executable_package_url: typing.Text
    @property
    def env_variables(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    def __init__(self,
        *,
        asset_name: typing.Text = ...,
        task_type: api.entity.task_pb2.Task.Type.ValueType = ...,
        run_id: typing.Optional[api.ids_pb2.RunId] = ...,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        fabric: typing.Text = ...,
        container_image_url: typing.Text = ...,
        executable_package_url: typing.Text = ...,
        env_variables: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","run_id",b"run_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","asset_name",b"asset_name","container_image_url",b"container_image_url","env_variables",b"env_variables","executable_package_url",b"executable_package_url","fabric",b"fabric","run_id",b"run_id","task_type",b"task_type"]) -> None: ...
global___ExecuteRequest = ExecuteRequest

class ExecuteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_ID_FIELD_NUMBER: builtins.int
    @property
    def job_id(self) -> api.ids_pb2.JobId: ...
    def __init__(self,
        *,
        job_id: typing.Optional[api.ids_pb2.JobId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["job_id",b"job_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["job_id",b"job_id"]) -> None: ...
global___ExecuteResponse = ExecuteResponse

class CheckStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    JOB_ID_FIELD_NUMBER: builtins.int
    @property
    def job_id(self) -> api.ids_pb2.JobId: ...
    def __init__(self,
        *,
        job_id: typing.Optional[api.ids_pb2.JobId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["job_id",b"job_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["job_id",b"job_id"]) -> None: ...
global___CheckStatusRequest = CheckStatusRequest

class CheckStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    FAILURE_REASON_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.JobId: ...
    status: api.entity.task_pb2.Task.Status.ValueType
    failure_reason: typing.Text
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.JobId] = ...,
        status: api.entity.task_pb2.Task.Status.ValueType = ...,
        failure_reason: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["failure_reason",b"failure_reason","id",b"id","status",b"status"]) -> None: ...
global___CheckStatusResponse = CheckStatusResponse
