[tool.poetry]
name = "tanmatsu"
version = "0.0.1"
description = "Declarative Terminal User Interface Library"
authors = ["snowdrop4 <82846066+snowdrop4@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.11"
"tri.declarative" = "^5.0"
parsy = "^1.3.0"
wcwidth = "^0.2"

[tool.poetry.dev-dependencies]
sphinx = "^5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
