
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-31T23:08:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e3b5a97fe20bb5ba4d73514695ddf1624f8eddd",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
