
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T10:37:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "457cbb767bd2ac44a36dfa4a844c1b21ae2416e0",
 "version": "1.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
