[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "grabngro"
version = "0.0.4"
authors = [
  { name="Andrew Yatzkan", email="andrew.yatzkan@gro-intelligence.com" },
]
description = "Python client library for quickly accessing small amounts of data from Gro Intelligence's agricultural data platform"
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Repository" = "https://github.com/gro-intelligence/gro-internal/tree/main/experimental/grabngro_package"
