# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetServiceGroupsResult',
    'AwaitableGetServiceGroupsResult',
    'get_service_groups',
    'get_service_groups_output',
]

@pulumi.output_type
class GetServiceGroupsResult:
    """
    A collection of values returned by getServiceGroups.
    """
    def __init__(__self__, entities=None, id=None, metadatas=None):
        if entities and not isinstance(entities, list):
            raise TypeError("Expected argument 'entities' to be a list")
        pulumi.set(__self__, "entities", entities)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if metadatas and not isinstance(metadatas, list):
            raise TypeError("Expected argument 'metadatas' to be a list")
        pulumi.set(__self__, "metadatas", metadatas)

    @property
    @pulumi.getter
    def entities(self) -> Sequence['outputs.GetServiceGroupsEntityResult']:
        return pulumi.get(self, "entities")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def metadatas(self) -> Sequence['outputs.GetServiceGroupsMetadataResult']:
        return pulumi.get(self, "metadatas")


class AwaitableGetServiceGroupsResult(GetServiceGroupsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetServiceGroupsResult(
            entities=self.entities,
            id=self.id,
            metadatas=self.metadatas)


def get_service_groups(metadatas: Optional[Sequence[pulumi.InputType['GetServiceGroupsMetadataArgs']]] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetServiceGroupsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['metadatas'] = metadatas
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
        if opts.plugin_download_url is None:
            opts.plugin_download_url = _utilities.get_plugin_download_url()
    __ret__ = pulumi.runtime.invoke('nutanix:index/getServiceGroups:getServiceGroups', __args__, opts=opts, typ=GetServiceGroupsResult).value

    return AwaitableGetServiceGroupsResult(
        entities=__ret__.entities,
        id=__ret__.id,
        metadatas=__ret__.metadatas)


@_utilities.lift_output_func(get_service_groups)
def get_service_groups_output(metadatas: Optional[pulumi.Input[Optional[Sequence[pulumi.InputType['GetServiceGroupsMetadataArgs']]]]] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetServiceGroupsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
