
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-07-27T06:23:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0afff1ff75b2c9e6a73582cbba687c902488b63e",
 "version": "2.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
