[build-system]
requires = [
   "setuptools>=56",
   "wheel",
   "matplotlib>=3.4.2",
   "numpy>=1.21.1",
   "pandas>=1.3.1",
   "pint>=0.18",
   "plotly==5.9.0",
   "scipy>=1.7.1",
   "seaborn>=0.11.2",
   "sympy>=1.8"

]
build-backend = "setuptools.build_meta"