
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-02T13:10:51+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0086ca45e09e07d91c8a05898b308ab7ad725788",
 "version": "0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
