[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aifund"
version = "0.0.4"
authors = [
  { name="yebaige", email="silence_tiano@163.com" },
]
description = "A AI fund"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/silenceTiano/aifund"
"Bug Tracker" = "https://github.com/silenceTiano/aifund/issues"