
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-26T10:33:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a63fb6befb35ca90f4bfb0a230adfb8a5b4fe56d",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
