
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-28T14:45:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dbf2382036ab14cf0d5a997b6034e9a72abbfa1",
 "version": "2.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
