[tool.poetry]
name = "procmanager"
version = "1.0.5"
description = "Helps starting & stopping programs"
authors = ["fdev31 <fdev31@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
procmgr = 'procmanager:main'

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
