[project]
name = "fundamental_gen"
version = "0.0.1"
authors = [
  { name="Vuong Nguyen", email="tienvuong.gt@gmail.com" },
]
description = "Fundamental genarator"
readme = "README.rst"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/tienvuong-vn/yahoofinancials"
"Bug Tracker" = "https://github.com/tienvuong-vn/yahoofinancials"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"