[build-system]
requires = ["setuptools", "wheel"]

[tool.isort]
known_third_party = ["cobra", "escher", "importlib_resources", "matplotlib", "numpy", "optlang", "pandas", "pytest", "setuptools"]
line_length = 80
indent = 4
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
lines_after_imports = 2
known_first_party = "optslope"
