
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-08-01T15:36:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6751b8a6467469081b351d24c08f474884406b6",
 "version": "2.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
