
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T19:37:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2e3ef5c1937f35330437a8fd429fc8206fea758",
 "version": "0.2.19.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
