[tool.poetry]
name = "hello_world"
version = "0.1.0"
description = ""
authors = ["Eng-Ahmad-Almohammad <almohammedahmed2@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
twine = "^4.0.1"
check-manifest = "^0.48"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
