[Global]
warp_direction = "y"
skip_synthtarget_affine = true
bandwidth = 6 # ABCD data uses 6, MSC data uses 10
distortion_correction_step_size = [3.0, 1.0, 0.1]
distortion_correction_shrink_factors = "2x1"
distortion_correction_smoothing = "0x0"

[omni_pipeline]
use_allineate = true
atlas = "trio"
data_resolution = 3.0
combine_sessions = false # false for ABCD data, true for MSC data
