
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T16:30:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c26cdc824a0fa5f14125c97f2cb372abceed140e",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
