[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "generate-kat-core"
version = "0.0.4"
description = ""
readme = "README.md"
authors = []
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "Jinja2 == 3.0.1",
]
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["generate_kat_core*"]
exclude = ["githooks"]
namespaces = false

[tool.bumpver]
current_version = "0.0.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"setup.py" = [
    "{version}",
]
