
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T21:11:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3be0d399330ae85880dc84bafda9931b93a71844",
 "version": "2.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
