dist: focal

language: python
jdk: openjdk10

cache:
  directories:
    - $HOME/.cache/pip

git:
  depth: false

jobs:
  include:
    - stage: test
      python: "3.6"
      script:
        - jdk_switcher use openjdk10
        - sh test.sh
    - # stage name not required
      python: "3.7"
      script: sh test.sh
    - # stage name not required
      python: "3.8"
      script: sh test.sh
    - # stage name not required
      python: "3.9"
      script: sh test.sh
    - # stage name not required
      python: "3.10"
      script: sh test.sh
    - # stage name not required
      python: "pypy"
      script: sh test.sh
      if: env(deploy) IS NOT present
    - # stage name not required
      python: "pypy3"
      script: sh test.sh
      if: env(deploy) IS NOT present
    - stage: deploy
      python: "3.6"
      script: skip
      if: env(deploy) IS present
      deploy:
        - provider: script
          script: sh deploy.sh
        - provider: releases
          api_key: $GH_ACCESS_TOKEN
          tag_name: $deploy
