[tool.poetry]
name = "phrase-translator"
version = "0.1.1"
description = "A very simple package to translate single words and phrases between different languages."
readme = "README.md"
authors = ["Fabian Richter <me@fr2501.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
