[project]
name = "FastaFragmentor"
version = "0.0.4"
authors = [
  { name="Carsten Fortmann-Grote", email="carsten.fortmann-grote@evolbio.mpg.de" },
  { name="Pabitra Nandy", email="nandy@evolbio.mpg.de"}
]
description = "Split fasta sequences into fragments of given length."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.gwdg.de/mpievolbio-scicomp/FastaDigest"
"Bug Tracker" = "https://gitlab.gwdg.de/mpievolbio-scicomp/FastaDigest/issues"
