[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "btcprompt"
authors = [{name = "cryptothink", email = "cryptothink629@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]

dependencies = ["beautifulsoup4"]

[project.urls]
Home = "https://github.com/cryptothink629"


[project.scripts]
btcprompt = "btcprompt.run:main"
