# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\.\couchbase_version.py
# at
#    2022-08-02 12:37:21.213615
__version__ = '4.0.3rc1'