
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T09:07:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "26b77f8bab40a6230e97143cd129a1ad4b8a750f",
 "version": "4.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
