[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "earthquake_latest_indonesia"
version = "0.0.2"
authors = [
  { name="FSI", email="paijo2012@gmail.com" },
]
description = "A small package earthquake latest indonesia"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/farissahaluddin/earthquake-detection"
"Bug Tracker" = "https://github.com/farissahaluddin/earthquake-detection/issues"